# encoding:utf-8
# create date: 2021-12-14 
# by NK
# Book: xwg538 exame keyword
class system:
        BOOK_NAME = "xwg 538 exame keyword"
        BOOK_TAG = "xwg538"
        def __init__(self):
                pass
        def bookWordsFirst(self):
                words = (
                        ["resemble",r"像，与……相似","like,look like,be similar to"],
                        ["recognize",r"认出，识别；承认","perceive,acknowledge,realize,appreciate,admit,identify,comprehend,understand,know"],
                        ["adjust",r"调整，使合适","change,modify,shift,alter"],
                        ["approach",r"方法","method,way"],
                        ["fundamental",r"基本的，基础的","rudimentary,preliminary,basic"],
                        ["rely on",r"依赖，依靠","depend on"],
                        ["domestic",r"家庭的，国内的","home,local,national"],
                        ["measure",r"测量","calculate,assessm,evaluate"],
                        ["trait",r"特性，特征","characteristic,feature,property"],
                        ["coin",r"创造，硬币","first used, invent"],
                        ["artificial",r"人造的，仿造的","synthetic,man-made"],
                        ["prompt",r"促进，激起","initiate，immediately"],
                        ["exchange",r"交换","share,apply A to B"],
                        ["underlie",r"成为什么的基础","based on,ground,root"],
                        ["ignore",r"忽视，不顾","neglect,overlook,underestimate"],
                        ["fertiliser",r"化肥，肥料","chemical,toxic,unnatural"],
                        ["that",r"那；那个","this,it,they,those,these,such"],
                        ["and",r"和，而且","or,as wellas ,both...and,not only...but also...,other than,in addition,besides,on the one hand ....on the other hand....neigher...nor..."],
                        ["rather than",r"而非，不是","but,yet,however,whereas,nonetheless,neverthelss,notwithstanding,although,though,instead"],
                        ["thanks to",r"由于，幸亏","stem from,derive,owingto , due to,according to ,because of , an accountof ,as a result of, leading to , because, since, for, in that, as, therefore,hence"]
                        )
                return words
        def bookWordsSecond(slef):
                words = (
                        ["diversity",r"多样性，差异","variety,difference"],
                        ["detect",r"查明，发现","find,look for, seek,scarch"],
                        ["isolate",r"使隔离，使孤立","inaccessible"],
                        ["avoid",r"避免","sacape,evitable"],
                        ["budget",r"预算","fund,financial"],
                        ["adapt to",r"使适应","fit,suit"],
                        ["alternative",r"供替代的，供选择的，替代品","substitute"],
                        ["compensate",r"补偿，赔偿","make up,offset"],
                        ["conponent",r"成分，要素","proportion"],
                        ["military",r"军事的","weapon,army"],
                        ["criteria",r"标准","standard"],
                        ["curriculum",r"课程","syllabus , course of study"],
                        ["feasible",r"可行的","realistic,viable"],
                        ["constrain",r"束缚，限制","stop,control"],
                        ["deficiency",r"缺陷，缺点","shortage,defect,weakness"],
                        ["supplement",r"补充","provision"],
                        ["distinguish",r"区别，辨别","separate,differentiate"],
                        ["analyze",r"分析，解释","examine,diagnose"],
                        ["emphasize",r"强调，着重","focus on,stress"],
                        ["enormous",r"庞大的，巨大的","massive,large"],
                        ["imitate",r"模仿","mimic,copy"],
                        ["hinder",r"阻碍","impede,prevent,deter,obstacle"],
                        ["legitimate",r"合法的","legal"],
                        ["limitation",r"限制","restrication"],
                        ["convention",r"手法；习俗","method,tradition"],
                        ["demanding",r"苛求的","troublesome"],
                        ["determine",r"决定","decide"],
                        ["accelerate",r"加速，促进，强调","speed up"],
                        ["ancient",r"古老的，古代的","aged,old"],
                        ["beneficial",r"有益的","helpful,advantageous,wholesome"],
                        ["chronic",r"慢性的，长期性的","lasting"],
                        ["conscious",r"有意识的，神志清醒的","aware,knowing"],
                        ["minimize",r"最小化，使……见效到最小的","reduce,lessen"],
                        ["immunity",r"免疫力","resistance"],
                        ["imperative",r"必要的，紧急的","compelling,neccessary,urgent"],
                        ["secrete",r"分泌","discharge,exude"],
                        ["exaggerate",r"夸大，夸张","overstate"],
                        ["transmit",r"传达，传输","pass,send,transfer"],
                        ["extinct",r"灭绝","die out , lost"],
                        ["exclusive",r"独有的；排外的；专一的","only"],
                        ["guarantee",r"保证，担保","assure"],
                        ["inherit",r"继承","receive"],
                        ["witness",r"见证，证据，目击者","view,see"],
                        ["magnetic",r"有磁性的","attractive"],
                        ["loss",r"减少；亏损；失败；遗失","waste,gone"],
                        ["option",r"选择","choice"],
                        ["prefer to",r"更喜欢","rather"],
                        ["priority",r"优先权","preference,preferential"],
                        ["primary",r"主要的","principal,main"],
                        ["principle",r"原理","rule"],
                        ["potential",r"潜能，潜在的","possibility"],
                        ["quantity",r"量，数量","number"],
                        ["settle",r"解决，定居","fix,figure out"],
                        ["sophisticate",r"使复杂","complicate"],
                        ["specific",r"明确的，特殊的","detailed,particular"],
                        ["survive",r"存活，幸存","remain"],
                        ["swift",r"迅速的，敏捷的，立刻的","quick,rapid"],
                        ["unexpectedly",r"出乎意料地","suprising"],
                        ["surrounding",r"环境","setting,environment"],
                        ["attempt",r"试图，尝试","try,test"],
                        ["expertise",r"专门技术","knowledge,skill"],
                        ["faculty",r"能力，才能，全体教员","ability"],
                        ["donate",r"捐赠","contribute"],
                        ["dynamics",r"动力学","energy,force,move"],
                        ["incentive",r"刺激，激励，动机","motive,stimulus"],
                        ["mortality",r"死亡率","death"],
                        ["peripheral",r"外围的，主要的","unimportant,minor"],
                        ["vichinity",r"临近的，附近","neighourhood,nearby"],
                        ["threaten",r"威胁，危及","endanger,jeopardize,risk,hazard"],
                        ["practice",r"练习，实行","method,exercise"],
                        ["bacteria",r"细菌","virus,germ,microbe"],
                        ["be subject to",r"受……的支配","face"],
                        ["be liable to",r"易于……","potential"],
                        ["innate",r"天生的，直觉的，内在的","built-in,inborn"],
                        ["pattern",r"模式","formation"],
                        ["therapy",r"治疗，理疗","treatment"],
                        ["original",r"原始的，最初的","initial,first"],
                        ["confidential",r"机密的，秘密的","undisclosed,secret,hidden"],
                        ["cognitive",r"认知的","mental"],
                        ["comply with",r"照做，遵守","obey"],
                        ["consult",r"查阅，商量，请教咨询","ask for advice"],
                        ["superior",r"上级的，优秀的","higher,upper"],
                        ["co-operation",r"合作，协作","support,work together"],
                        ["co-ordinate",r"使……协调","organize,harmonize"],
                        ["differ",r"使……相异,使……不同","vary"],
                        ["cue",r"线索","hint,clue"],
                        ["signal",r"信号","symbol,mark,sign"],
                        ["abandon",r"放弃，遗弃","quit,give up, forsake,derelicat"],
                        ["halt",r"停止","stop,quit"],
                        ["fragile",r"脆弱的","vulnerable"],
                        ["retain",r"记住","maintain"],
                        ["vanish",r"消失，绝迹","disappear"],
                        ["delivery",r"递送","send"],
                        ["erode",r"侵蚀","rust,damage"],
                        ["induce",r"引起，引诱","cause,lead to "],
                        ["stable",r"稳定的","constant,unchanged"],
                        ["integrate",r"使……成整体","combine,whole"],
                        ["equal",r"平等的；相等的；胜任的","fair,even"],
                        ["grant",r"拨款；授予","offer"],
                        

                )
                return words

        def bookWordsThird(self):
                words = (
                        ["accumulate v累积 积聚 ","gather"],
                        ["addictive","adj.上瘾的","habit"],
                        ["adversity","n.逆境 不幸","trouble"],
                        ["aggression","n.侵犯 侵害","attack"],
                        ["agreeable","adj.令人愉快的;适合的;和蔼可亲的 ","pleasant"],
                        ["aid","n.援助帮助","help"],
                        ["allergic","adj.过敏的;对……极讨厌的","irritate"],
                        ["altitude n.高度;海拔","height"],
                        ["application","n应用","utilization"],
                        ["approve","批准","agree"],
                        ["array","n.排列;大批","order"],
                        ["assign","u分配;指派","allocate"],
                        ["association","n.协会 联盟;联系","union"],
                        ["attitude","1.看法 态度","opinion"],
                        ["authority",".当局 权威","government"],
                        ["be consisten with","与……一致","compatible"],
                        ["bear","承担;忍受","tolerate"],
                        ["blight","损害;枯萎","destroy"],
                        ["boundary","n.边界;底线","barrier"],
                        ["bungle","搞糟 拙劣地工作","mishandle"],
                        ["burden","n.负担","load"],
                        ["calamity","n.灾难","disaster"],
                        ["capacity","n.容量","volume"],
                        ["catastrophic","adj.灾难的","disastrous"],
                        ["cater","迎合;满足需要","serve"],
                        ["certify","证明 保证","verify"],
                        ["civic","adj.市民的","municipal"],
                        ["comment","n.评论;意见评论","remark"],
                        ["commitment","n.承诺 许诺 义务;致力 engagement"],
                        ["communal","adj.公共的 公社的","public"],
                        ["commute","通勤;用……交换","travel"],
                        ["compare"," 与……相比较","contrast"],
                        ["conceal","隐藏;隐瞒","hide"],
                        ["concentrate 专心于;集中","focus"],
                        ["concur","同意","agree"],
                        ["confer","授予 给予","grant"],
                        ["conflict","n.冲突 矛盾","unharmonious"],
                        ["confuse","使混乱 使迷惑","puzzle"],
                        ["conservative","adj.保守的","traditional"],
                        ["considerable","adj相当大的 重要的","significant"],
                        ["contingent","adj.因情况而异的","uncertain"],
                        ["controversial","adj.有争论的","disputable"],
                        ["correlation","n.相关 关联","link"],
                        ["courtship","n.求爱(时期)","mate"],
                        ["crash","n.碰撞","collapse"],
                        ["credibility","n.可信性","reliance"],
                        ["criminal","n.罪犯 犯人","conviction"],
                        ["crisis","n.危机","risk"],
                        ["criticism","n.批评","condemn"],
                        ["curb","限制 抑制","restrict"],
                        ["damp","adj.潮湿的","wet"],
                        ["dazzle"," 使目眩;使……眼花","flash"],
                        ["deadline","n.最后期限","limit"],
                        ["delay","n.延期 耽搁","postpone"],
                        ["democratic","adj.民主的","republic"],
                        ["adj.人口统计学的;","population statistic"],
                        ["demographic","人口学的"],
                        ["dental","adj.牙科的 牙齿的","teeth"],
                        ["depression","n.抑郁 沮丧","frustration"],
                        ["designate","指定 指派 标出","appoint"],
                        ["detain 留住","hold"],
                        ["devastate","毁坏 毁灭","wreck"],
                        ["disclose","北公开;揭露","expose"],
                        ["disparate","adj不同的","different"],
                        ["display","disrupt","破坏","n.显示","show","destroy"],
                        ["distract"," 转移 分心","divert"],
                        ["distribute","分配 分发","spread"],
                        ["documentation","n.文件;文献","record"],
                        ["domain","n.领域","field"],
                        ["dominan.adj占支配地位的 占优势的 overbearing"],
                        ["dramatic adj.戏剧化的;激动人心的;引人注意的","striking"],
                        ["drought","n干旱","dry"],
                        ["durable","adi持久的","lasting"],
                        ["eco-friendly adj生态友好的环保的 environmentally-friendly"],
                        ["elaborate v.详细阐述 详细叙述 illustrate"],
                        ["elderly","adj.高龄的","aged"],
                        ["eliminate","消除 排除","dispose"],
                        ["elusive","adj难懂的 难捉摸的;行踪隐秘的","hard"],
                        ["encyclopaedia","1.百科全书","entire range of knowledge"],
                        ["entrepreneur","n.企业家","boss"],
                        ["equator","n.赤道","geography"],
                        ["erratically","adv 不定地 无规律地","unpredictably"],
                        ["established","adj.确定的;已制定的 已建立的 built"],
                        ["estate","n.房地产","property"],
                        ["ethical","adj道德的","moral"],
                        ["eventually","ady最后 终于","finally"],
                        ["evidence","n.迹象;证据","proof"],
                        ["evolve","进化 发展;逐渐形成","develop"],
                        ["exceptional","adj.异常的 特别出色的","extreme  utmost"],
                        ["exhausted","adj.疲惫的 耗尽的","fatigue"],
                        ["experiment","n.实验 试验","test"],
                        ["explicit","adj.明确的","clear"],
                        ["exploit","开发 利用","use"],
                        ["extend","扩展 延伸 推广","expand"],
                        ["extract","n摘录","提取","quotation"],
                        ["famine","n.饥荒","hunger"],
                        ["finite","adj.有限的","limited"],
                        ["fitness",".健康","health"],
                        ["foe","n.敌人 危害物","enemy"],
                        ["format","n.格式","structure"],
                        ["fragment","碎片","piece"],
                        ["freeze","n.冰冻 冻结","chill"],
                        ["fulfill","满足 实现","execute"],
                        ["gene","基因","factor"],
                        ["gifted","adj、有天赋的 有才华的","talented"],
                        ["graphic","adj形象的;图解的picture"],
                        ["habitat","n.栖息地 住处","residence"],
                        ["harbour","海港;怀有 hold"],
                        ["hardship","n.困苦;苦难","difficult"],
                        ["harsh","adj艰难的;严酷的","rough"],
                        ["hypothesis","n.假设","assumption"],
                        ["impact","n.影响","influence"],
                        ["impressive","adj.感人的;给人","深刻印象的","touching"],
                        ["in|accordance|with 依照;与……一致","conform"],
                        ["inaccurate","adj.错误的","incorrect"],
                        ["inactive","adj.不活跃的;不活动的","passive"],
                        ["inappropriate","adj.不适当的","hard"],
                        ["indulge","v沉溺(于)"," spoil"],
                        ["infest","侵害;寄生于","plague"],
                        ["installment","n.安装;分期付款","paymen.on its completion"],
                        ["intelligence","n.智力","mind"],
                        ["intense","adj.强烈的;紧张的;热情的","strong"],
                        ["interaction n.相互作用;交流互动","social activities"],
                        ["interference","n.干涉","interdependence"],
                        ["interior","adj.内部的;n.内部","inner"],
                        ["interrupt","v中断","stop"],
                        ["introverted","adj.内向的;含蓄的","shyness"],
                        ["involve","包含;牵涉","associate"],
                        ["keen adj.热切的;急迫的;强烈的","strong"],
                        ["label","打上标签","display"],
                        ["lack","缺乏;不足","shortage"],
                        ["landscape","n.风景","scene"],
                        ["likelihood","n.可能性","chance"],
                        ["limb","n.四肢","arm or leg"],
                        ["linguistic","adj.语言(学)的","language"],
                        ["log","n.原木;记录","record"],
                        ["look-in","n.成功的机会","opportunity  chance"],
                        ["lopsided","adj.不平衡的","uneven"],
                        ["mainly","ad主要地 大体上","primarily"],
                        ["malfunction","u发生故障;不起作用"," breakdown"],
                        ["mammal","n.哺乳动物","creature"],
                        ["manage to do","设法完成某事","success"],
                        ["manifest","出现 表现","obvious"],
                        ["manufacture","n.生产","produce"],
                        ["marine adj.海产的;航海的 海运的 sea"],
                        ["mate","n.配偶","spouse"],
                        ["mechanism","n.机制 原理","method"],
                        ["mental","adj.精神的 心理的","intelligent"],
                        ["mercury","n.汞 水银","liquid metal"],
                        ["meteorological","adj.气象学的","weather"],
                        ["migrate","转移 迁移","move"],
                        ["moisture","n.水分 湿度","humidity"],
                        ["monitor","监控","surveillance"],
                        ["motif","n.主题;图形","theme"],
                        ["mould","模压 塑造;塑造成","form"],
                        ["native","天然的;天赋的;adj.本国的;土著的;","original"],
                        ["nocturnal","发生的adj夜间的夜间 night"],
                        ["norm","n规范","regulation"],
                        ["notoriety","n.名声","famous"],
                        ["objective","adi","n.目标 目的","客观的","goal"],
                        ["obligation","n.义务","responsibility"],
                        ["obscure","掩盖 使模糊不清","hide"],
                        ["obtain","获得","get"],
                        ["odd","adj.古怪的","strange"],
                        ["odour","n.气味","smell"],
                        ["offensive","adj.冒犯的 无礼的","hostile"],
                        ["official","adj 官方的;n.官员","authority"],
                        ["optimum","n.最佳效果adj.最适宜的","best"],
                        ["ordinary adj.普通的;平凡的;平常的","common"],
                        ["organ","n.器官;机构","a|part|of|a|body"],
                        ["out|of|the|question","不可能","impossible"],
                        ["overcome","v克服","defeat"],
                        ["overtake","v赶上","surpass"],
                        ["paralyse","v.使……麻痹;使……瘫痪","cannot move"],
                        ["paramount","","adj.最重要的 主要的 principal"],
                        ["participate","参加","join"],
                        ["patient","容忍的n.病人;患者adj.有耐性的 能repetitive"],
                        ["peak"," 使……达到顶峰n.最高峰 顶点","top"],
                        ["permit","许可","n.许可证 执照","allow"],
                        ["persuade","说服 劝说","influence"],
                        ["pessimistic","adj.悲观的","negative"],
                        ["phase","n 阶段","process"],
                        ["physical","质的","adj.身体上的;物","body"],
                        ["plagiarise","抄袭","copy"],
                        ["plenty of","大量的","many"],
                        ["plot","v密谋","plan"],
                        ["pose","提出;造成;形成","cause"],
                        ["portable","adj.便携的","conveyable"],
                        ["poverty","n.贫穷","poor"],
                        ["praise","n.赞扬","commend"],
                        ["predict","预测 预知","expect"],
                        ["pressing","adj.迫切的","urgent"],
                        ["private","adj.私人的;私有的;私下的","personal"],
                        ["prohibit","禁止","not|allowed"],
                        ["prolong","拉长;延长","extend"],
                        ["promote","促进;推销","improve"],
                        ["prosper","使成功;使繁荣","success"],
                        ["purify","净化","clean "],
                        ["qualify","取得资格","fulfill"],
                        ["radical","adj.彻底的;根本的","utmost"],
                        ["range","n:范围;幅度","scope"],
                        ["rare","adj.稀有的","unusual"],
                        ["rate","评估n.等级","rank;measure"],
                        ["react","反应","respond"],
                        ["recreation","n.娱乐;消遣","entertainment"],
                        ["reduction","n.下降;减少","decrease"],
                        ["refer|to","提及指(的是);涉及;","talk about"],
                        ["rehearsal","n.排演;预演;练习","preparation"],
                        ["reject","拒绝;排斥;丢弃","exclude"],
                        ["relevant","adj.相关的","relative"],
                        ["religious","adj.宗教的;虔诚的","sacred"],
                        ["reluctant","adj.不情愿的","unwilling"],
                        ["reproduce","繁殖","breed"],
                        ["responsible","adj.负责的;可靠的;有责任的","liable"],
                        ["revision","n.修正","editing"],
                        ["revive","使复苏;恢复","renaissance"],
                        ["ruin","v毁灭","destroy"],
                        ["scenic","adj.风景优美的","beautiful"],
                        ["shade","n.遮阳;阴影","shelter"],
                        ["skepticism","n.怀疑","doubt"],
                        ["soar","激增","increase"],
                        ["solely","adv唯一地","alone"],
                        ["solicitor","n.律师","lawyer"],
                        ["steer","控制;引导","manage"],
                        ["stimulate","u刺激;激励","motivate"],
                        ["stride","n.进展","progress"],
                        ["succumb","vi.屈服","yield"],
                        ["subdivide",";把……细分"," break down"],
                        ["subtle","adj.微妙的","delicate"],
                        ["substance","n.物质;实质","matter"],
                        ["sufficiency","n.足量;充足","enough"],
                        ["supersede","取代;代替","replace"],
                        ["suppress","v抑制;隐瞒","hold"],
                        ["supremacy","n.至高无上;很高的地位 priority"],
                        ["suspicious","adj.可疑的","odd"],
                        ["sustainable","adj.可持续的","long-term"],
                        ["symptom","n.症状;征兆","sign"],
                        ["tension","n.紧张;不安","upset"],
                        ["term","n.术语","word"],
                        ["throughout"," adv:自始至终;到处;全部prep.贯穿;遍及","anywhere"],
                        ["toll","征收n.通行费","charge"],
                        ["trace","n.追溯;痕迹","track"],
                        ["transcend","胜过;超越","excel"],
                        ["transit","运送n.运输;经过","send"],
                        ["tremendous","adj.巨大的;惊人的","vast"],
                        ["trigger","n.触发;引发;引起","begin"],
                        ["tropical","adj.热带的","hot"],
                        ["unbiased","adj.公正的，无偏见的","fair"],
                        ["uniform","adj.始终如一的","consistent"],
                        ["valuable","adj.宝贵的，有价值的","benefit"],
                        ["versatile","adj.多功能的","all-around"],
                        ["view","u.看","","overlook"],
                        ["violent","adj.暴力的;猛烈的","fierce"],
                        ["visible","adj明显的，看得见的","see"],
                        ["visual","adj.视觉的","image"],
                        ["well-being","n.健康，康乐","health"]
                     )
                return words
