# encoding:utf-8
# create date: 2021-12-14 
# by NK
# Book: 学为贵538考点词
class system:
        BOOK_NAME = "学为贵538考点词"
        BOOK_TAG = "xwg538"
        def __init__(self):
                pass
        def bookWordsFirst(self):
                words = (
                        ["resemble",r"像，与……相似","like,look like,be similar to"],
                        ["recognize",r"认出，识别；承认","perceive,acknowledge,realize,appreciate,admit,identify,comprehend,understand,know"],
                        ["adjust",r"调整，使合适","change,modify,shift,alter"],
                        ["approach",r"方法","method,way"],
                        ["fundamental",r"基本的，基础的","rudimentary,preliminary,basic"],
                        ["rely on",r"依赖，依靠","depend on"],
                        ["domestic",r"家庭的，国内的","home,local,national"],
                        ["measure",r"测量","calculate,assessm,evaluate"],
                        ["trait",r"特性，特征","characteristic,feature,property"],
                        ["coin",r"创造，硬币","first used, invent"],
                        ["artificial",r"人造的，仿造的","synthetic,man-made"],
                        ["prompt",r"促进，激起","initiate，immediately"],
                        ["exchange",r"交换","share,apply A to B"],
                        ["underlie",r"成为什么的基础","based on,ground,root"],
                        ["ignore",r"忽视，不顾","neglect,overlook,underestimate"],
                        ["fertiliser",r"化肥，肥料","chemical,toxic,unnatural"],
                        ["that",r"那；那个","this,it,they,those,these,such"],
                        ["and",r"和，而且","or,as wellas ,both...and,not only...but also...,other than,in addition,besides,on the one hand ....on the other hand....neigher...nor..."],
                        ["rather than",r"而非，不是","but,yet,however,whereas,nonetheless,neverthelss,notwithstanding,although,though,instead"],
                        ["thanks to",r"由于，幸亏","stem from,derive,owingto , due to,according to ,because of , an accountof ,as a result of, leading to , because, since, for, in that, as, therefore,hence"]
                        )
                return words
        def bookWordsSecond(slef):
                words = (
                        ["diversity",r"多样性，差异","variety,difference"],
                        ["detect",r"查明，发现","find,look for, seek,scarch"],
                        ["isolate",r"使隔离，使孤立","inaccessible"],
                        ["avoid",r"避免","sacape,evitable"],
                        ["budget",r"预算","fund,financial"],
                        ["adapt to",r"使适应","fit,suit"],
                        ["alternative",r"供替代的，供选择的，替代品","substitute"],
                        ["compensate",r"补偿，赔偿","make up,offset"],
                        ["conponent",r"成分，要素","proportion"],
                        ["military",r"军事的","weapon,army"],
                        ["criteria",r"标准","standard"],
                        ["curriculum",r"课程","syllabus , course of study"],
                        ["feasible",r"可行的","realistic,viable"],
                        ["constrain",r"束缚，限制","stop,control"],
                        ["deficiency",r"缺陷，缺点","shortage,defect,weakness"],
                        ["supplement",r"补充","provision"],
                        ["distinguish",r"区别，辨别","separate,differentiate"],
                        ["analyze",r"分析，解释","examine,diagnose"],
                        ["emphasize",r"强调，着重","focus on,stress"],
                        ["enormous",r"庞大的，巨大的","massive,large"],
                        ["imitate",r"模仿","mimic,copy"],
                        ["hinder",r"阻碍","impede,prevent,deter,obstacle"],
                        ["legitimate",r"合法的","legal"],
                        ["limitation",r"限制","restrication"],
                        ["convention",r"手法；习俗","method,tradition"],
                        ["demanding",r"苛求的","troublesome"],
                        ["determine",r"决定","decide"],
                        ["accelerate",r"加速，促进，强调","speed up"],
                        ["ancient",r"古老的，古代的","aged,old"],
                        ["beneficial",r"有益的","helpful,advantageous,wholesome"],
                        ["chronic",r"慢性的，长期性的","lasting"],
                        ["conscious",r"有意识的，神志清醒的","aware,knowing"],
                        ["minimize",r"最小化，使……见效到最小的","reduce,lessen"],
                        ["immunity",r"免疫力","resistance"],
                        ["imperative",r"必要的，紧急的","compelling,neccessary,urgent"],
                        ["secrete",r"分泌","discharge,exude"],
                        ["exaggerate",r"夸大，夸张","overstate"],
                        ["transmit",r"传达，传输","pass,send,transfer"],
                        ["extinct",r"灭绝","die out , lost"],
                        ["exclusive",r"独有的；排外的；专一的","only"],
                        ["guarantee",r"保证，担保","assure"],
                        ["inherit",r"继承","receive"],
                        ["witness",r"见证，证据，目击者","view,see"],
                        ["magnetic",r"有磁性的","attractive"],
                        ["loss",r"减少；亏损；失败；遗失","waste,gone"],
                        ["option",r"选择","choice"],
                        ["prefer to",r"更喜欢","rather"],
                        ["priority",r"优先权","preference,preferential"],
                        ["primary",r"主要的","principal,main"],
                        ["principle",r"原理","rule"],
                        ["potential",r"潜能，潜在的","possibility"],
                        ["quantity",r"量，数量","number"],
                        ["settle",r"解决，定居","fix,figure out"],
                        ["sophisticate",r"使复杂","complicate"],
                        ["specific",r"明确的，特殊的","detailed,particular"],
                        ["survive",r"存活，幸存","remain"],
                        ["swift",r"迅速的，敏捷的，立刻的","quick,rapid"],
                        ["unexpectedly",r"出乎意料地","suprising"],
                        ["surrounding",r"环境","setting,environment"],
                        ["attempt",r"试图，尝试","try,test"],
                        ["expertise",r"专门技术","knowledge,skill"],
                        ["faculty",r"能力，才能，全体教员","ability"],
                        ["donate",r"捐赠","contribute"],
                        ["dynamics",r"动力学","energy,force,move"],
                        ["incentive",r"刺激，激励，动机","motive,stimulus"],
                        ["mortality",r"死亡率","death"],
                        ["peripheral",r"外围的，主要的","unimportant,minor"],
                        ["vichinity",r"临近的，附近","neighourhood,nearby"],
                        ["threaten",r"威胁，危及","endanger,jeopardize,risk,hazard"],
                        ["practice",r"练习，实行","method,exercise"],
                        ["bacteria",r"细菌","virus,germ,microbe"],
                        ["be subject to",r"受……的支配","face"],
                        ["be liable to",r"易于……","potential"],
                        ["innate",r"天生的，直觉的，内在的","built-in,inborn"],
                        ["pattern",r"模式","formation"],
                        ["therapy",r"治疗，理疗","treatment"],
                        ["original",r"原始的，最初的","initial,first"],
                        ["confidential",r"机密的，秘密的","undisclosed,secret,hidden"],
                        ["cognitive",r"认知的","mental"],
                        ["comply with",r"照做，遵守","obey"],
                        ["consult",r"查阅，商量，请教咨询","ask for advice"],
                        ["superior",r"上级的，优秀的","higher,upper"],
                        ["co-operation",r"合作，协作","support,work together"],
                        ["co-ordinate",r"使……协调","organize,harmonize"],
                        ["differ",r"使……相异,使……不同","vary"],
                        ["cue",r"线索","hint,clue"],
                        ["signal",r"信号","symbol,mark,sign"],
                        ["abandon",r"放弃，遗弃","quit,give up, forsake,derelicat"],
                        ["halt",r"停止","stop,quit"],
                        ["fragile",r"脆弱的","vulnerable"],
                        ["retain",r"记住","maintain"],
                        ["vanish",r"消失，绝迹","disappear"],
                        ["delivery",r"递送","send"],
                        ["erode",r"侵蚀","rust,damage"],
                        ["induce",r"引起，引诱","cause,lead to "],
                        ["stable",r"稳定的","constant,unchanged"],
                        ["integrate",r"使……成整体","combine,whole"],
                        ["equal",r"平等的；相等的；胜任的","fair,even"],
                        ["grant",r"拨款；授予","offer"],
                        

                )
                return words

