# encoding:utf-8
# create date: 2022-01-9
# by NK
# Book: ysw exame keyword
class system:
        BOOK_NAME = "ysw  keyword"
        BOOK_TAG = "ysw"
        def __init__(self):
                pass
        def bookWordsFirst(self):
                # ["1.nuon、verb、adj"]
                words = (
                        ["caravan","['karovacn]","n.房车"],
                        ["navigation","[,navr'gelfn]","n.导航"],
                        ["demonstration","[,demon'strerfn]","n.演示"],
                        ["candles","['kndls]","n. 蜡烛"],
                        ["canteen","[kan'tizn]","n.食堂"],
                        ["intermediate","[,nto'mi:drot]","adj.中级的"],
                        ["vegetarian","[,vedze'teerien]","n.素食主义者"],
                        ["campsite","['kampsait]","n.野营点"],
                        ["helicopter","['helrkopta(r)]","n.直升机"],
                        ["donations","[deu'nerfnz]","n.捐赠"],
                        ["moonlight","['mu:nlait]","n.月光"],
                        ["mid-range","['midreind3]","adj.中等距离的"],
                        ["warehouse","['weahaus]","n.仓库"],
                        ["double-grill","['dablgril]","n.双层烤架"],
                        ["researcher","[r's3:t∫э(r)]","n.研究员"],
                        ["website","['websart]","n.网站"],
                        ["charge","[tfa:dz]","v./n.充电/冲锋/费用"],
                        ["access","['ækses]","n.使用"],
                        ["bills","[brls]","n.账单"],
                        ["waitress","['wertres]","n.女服务生"],
                        ["excursion","[ik'sk3:fn]","n.远足"],
                        ["duration","[dju'rerfn]","n.持续"],
                        ["elevator","['elrverte(r)]","n.电梯"],
                        ["postage","['peustidzl","n.邮费"],
                        ["signature","['signetfo(r)]","n. 签字"],
                        ["liberty","['libati]","n. 自由"],
                        ["adventure","[od'ventfo(r)]","n. 冒险"],
                        ["automatic","[,o:te'matik]","adj. 自动的"],
                        ["painkillers","['pernkrlo(r)z]","n.止痛药"],
                        ["sailing","['serlm]","n. 远航"],
                        ["keyboard","['ki:bord]","n.键盘"],
                        ["transit","['tranzit]","n.运输"],
                        ["enjoyable","[in'dzorabl]","adj.令人愉快的;好玩的"],
                        ["snowboarding","['snevbo:dm]","n.滑雪(雪板)"],
                        ["landscape","['landskerp]","n.风景"],
                        ["helmet","['helmrt]","n.头盔"],
                        ["mask","[marsk]","n.面具"],
                        ["moderate","['moderat]","adj.温和的;中度的"],
                        ["ladder","['læde(r)1","n.梯子"],
                        ["concentration","[,konsn'trerfn]","n.注意力"],
                        ["categories","['katageriz]","n.分类;类别"],
                        ["variable","['veeriebl]","adj.变化的"],
                        ["sauna","['so:na]","n.桑拿"],
                        ["child-minding","['tfarldmaindin]","n.育儿"],
                        ["racket","['rakit]","n.球拍"],
                        ["coach","[keut Ã","n.车厢"],
                        ["handles","['handls]","n.把手"],
                        ["nylon","['narlon]","n.尼龙"],
                        ["package","['pakid3]","n.(话费，旅游等)套餐"],
                        ["receipt","[rr'si:t]","n.收据"],
                        ["waterfall","['wo:tofo:l]","n.瀑布"],
                        ["partner","['pa:tno(r)]","n.伙伴"],
                        ["voucher","['vaotfe(r)]","n.代金券"],
                        ["gym","[dzim]","n.健身房"],
                        ["laptop","['laptop]","n.笔记本电脑"],
                        ["yoga","['jooge]","n.瑜伽"],
                        ["knife","[narf]","n. 刀"],
                        ["neck","[nek]","n.脖子"],
                        ["mat","[mat]","n.垫子"],
                        ["container","[kon'tena(r)]","n.容器"],
                        ["buffet","['bofer]","n. 自助餐"],
                        ["enlargement","[in'la:dzment]","n.扩大"],
                        ["studio","['stju:drau]","n.工作室"],
                        ["critic","['kritik]","n.批评家"],
                        ["zoom","[zurm]","v./n.变焦"],
                        ["lens","[lenz]","n.镜头"],
                        ["infrastructure","['imfrastraktfe(r)]","n.基础设施"],
                        ["electricity","[1,lek'trisatr]","n.电"],
                        ["resort","[rr'zo:t]","n.旅游胜地"],
                        ["infection","[n'fek∫n]","n.传染，感染"],
                        ["fountain","['faunton]","n.喷泉"],
                        ["vest","[vest]","n.马甲"],
                        ["qualification","[,kwolifi'keifn]","n.资格"],
                        ["poverty","['povetr]","n.贫穷"],
                        ["expectation","[,ekspek'terfn]","n.期望"],
                        ["glue","[glu:]","n.胶水"],
                        ["font","[font]","n.字体"],
                        ["reliable","[rr'larabl]","adj. 可靠的"],
                        ["keyboard","['ki:bo:d]","n.键盘"],
                        ["violin","[,vara'lin]","n.小提琴"],
                        ["manufacturing","[,manjo'faktferinl","n.制造"],
                        ["outfit","['aotfit]","n.服装"],
                        ["shade","[ferd]","n.阴影，树荫"],
                        ["myth","[mr0]","n. 神话"],
                        ["opened","harvested['aopend]['ha:vistid]", "adj.收获的 adj.打开的"],
                        ["cleaned","[klirnd]","adj. 干净的;已清洁的"],
                        ["sealed cooled expanded","[sitld]"," adj. 密封的 n.密封"],
                        ["cooled","[ku:ld]","adj.冷却的"],
                        ["expanded","[rk'spandid]","adj.扩大的"],
                        ["segment","['segmant]","n.部分"],
                        ["disability","[,diso'brloti]","n.残疾"],
                        ["spine","[spain]","n. 脊柱"],
                        ["pest","[pest]","n.害虫"],
                        ["intermediate","[,mto'mi:diat]","adj.中间的"],
                        ["laundry","['lo:ndr]","n.洗衣"],
                        ["survey","['s3:ver]","n.调查"],
                        ["rape","[rerp]","n.强奸"],
                        ["pegs","[pegz]","n.钉桩;钉子"],
                        ["scaffold","['skeefould]","n.脚手架"],
                        ["hazel","['herzl]","n.榛子"],
                        ["portrait","['po:trert]","n.肖像"],
                        ["symbolism","['simbalizam]","n.象征主义;象征意义"],
                        ["mud","[mad]","n.泥土"],
                        ["variable","['veariabl]","adj./n.变量(的)"],
                        ["certificate","[sa'tufikat]","n.证书"],
                        ["liquids","['likwidz]","n.液体"],
                        ["plastic","['plastrk]","n.塑料"],
                        ["storage","['storridz]","n. 存储"],
                        ["Sweden","[swi:dan]","n.瑞典"],
                        ["vest","[vest]","n.背心"],
                        ["grocery","['growsari]","n.杂货店"],
                        ["socialise","['seufolarz]","v社交"],
                        ["lemon","['leman]","n. 柠檬"],
                        ["congratulations","[kon,gratfu'lerfnz]","n.祝贺"],
                        ["pump","[pamp]","n.泵"],
                        ["mat","mirror","[mæt]","['mirэ(r)]","n. 垫","n.镜子"],
                        ["map","[map]","n.地图"],
                        ["birdwatching","['b3:dwotfinl","n.观鸟"],
                        ["identification","[ar,dentifi'kerfn]","n.识别"],
                        ["moderate","['mpdarat]","adj.温和的"],
                        ["judo","['dzu:doo]","n.柔道"],
                        ["orientation","[,oirian'terfn]","n.新生入学会"],
                        ["instructor","[m'strakte(r)1","n.教练"],
                        ["waterproof","['wo:topru:f]","adj. 防水的"],
                        ["dirt","[d3:t]","n.泥土，灰尘"],
                        ["cracked","[krakt]","adj. 有裂痕的"],
                        ["spa","[spa:]","n.水疗，温泉疗养地"],
                        ["calendar","['kalmdo(r)]","n.日历"],
                        ["buffet","['bufer]","n.自助餐"],
                        ["napkin","['næpkin]","n.餐巾"],
                        ["vacancy","['verkensi]","n.空缺"],
                        ["clerical","['klerikl]","adj文书的"],
                        ["sector","['sekte(r)]","n.部门"],
                        ["complicated","['komplikertid]","adj.复杂的"],
                        ["administrative","[ed'mmistratrv]","adj.行政的"],
                        ["spreadsheet","['spredfi:t]","n.电子表格"],
                        ["sink","[sink]","n. 水槽"],
                        ["stove","[stauv]","n.火炉"],
                        ["frustrating","[fra'strertin]","adj.令人沮丧的"],
                        ["orchestra","['o:kistro]","n.管弦乐队"],
                        ["ballet","['baler]","n. 芭蕾舞"],
                        ["amateur","['æmete(r)]","n.业余的"],
                        ["composer","[kom'pavzэ(r)]","n.作曲家"],
                        ["posters","['poustaz]","n.海报"],
                        ["carpentry","['ka:pentri]","n.木工活"],
                        ["lifeguard","['larfga:d]","n.救生员"],
                        ["monument","['monjomont]","n.纪念碑"],
                        ["fountain","['faontan]","n. 喷泉"],
                        ["locker","['loke(r)]","n.有锁储物柜"],
                        ["fireplace","['faroplers]","n.壁炉"],
                        ["occupancy","['okjopenst]","n.居住，占据"],
                        ["hostel","['hostl]","n.旅店"],
                        ["water-ride","['wo:tarard]","n激流勇进"],
                        ["waterproof","['wo:tapru:f]","ad. 防水的"],
                        ["rollercoaster","['raula(r)'kausta(r)]","n.过山车"],
                        ["resort","[ri'zo:t]","n.胜地"],
                        ["anniversary","[,ant'v3:sar]","n周年"],
                        ["committee","[ka'miti]","n.委员会"],
                        ["off-peak","['of pi:k]","ad.非高峰的"],
                        ["towel","I'taval]","n.毛巾"],
                        ["all-in","L'a:lun]","ad. 包括一切的"],
                        ["hovercraft","['hovakra:ft]","n.气垫船"],
                        ["roadworthy","['raudw3:ö1)","ad适合上路的"],
                        ["overfill","l'auva(r)fil]","V填满"],
                        ["archaeology","[,a:ki'olad31]","n.考古学;"],
                        ["archeology","[,a:ki'olad31]","n.考古学;"],
                        ["classification","[,klasifikern]","n分类"],
                        ["coursework","['ko:sw3:k]","n.课程"],
                        ["cranberry","['kranbar1]","n蔓越莓"],
                        ["hazel","['herzl]","n.榛子"],
                        ["documentary","[, dokjo'mentri]","n.纪录片"],
                        ["dustbin","['dastbmn]","n.垃圾箱"],
                        ["garbage","['ga:bid3]","n垃圾"],
                        ["dirt","[d3:t]","n. 灰尘"],
                        ["fertilisers","I'f3:tolarzaz]","n.化肥"],
                        ["fernery","[f3:nari]","n.蕨类植物"],
                        ["corrections","[ka'rek(nz]","n改正"],
                        ["theoretical","[,Ora'retikl]","ad.理论的"],
                        ["region","['ritdzan]","n.地区"],
                        ["assignment","[a'saumant]","n. 作业"],
                        ["miniature","['minatfa(r)]","n.缩微景观"],
                        ["biscuit","['biskit]","n饼干"],
                        ["canoe","[ka'nux]","n.独木舟"],
                        ["donation","[daw nerfn]","n捐赠"],
                        ["labels","['lerbls]","n.标签"],
                        ["luxury","['lakfarr]","n. 奢华"],
                        ["lock-up","[lokAp]","adi.带锁的"],
                        ["warehouse","['weahaos]","n.仓库"],
                        ["ferries","['ferrs]","n.轮渡"],
                        ["comfortable","['kAmftabll","ad'.舒适的"],
                        ["preservation","[, preza ver{n]","n.保留，保存"],
                        ["authority","[o: Opratil","n.权威"],
                        ["flamingo","[fla mingao]","n.火烈鸟"],
                        ["trails","[treils]","n踪迹"],
                        ["poster","['pausta(r)]","n.海报"],
                        ["altitude","L'æltitju:d]","n.高度"],
                        ["vegetation","[,vedza'terfn]","n.植被"],
                        ["calligraphy","[ka'ligrafil","n. 书法"],
                        ["caravan","['karavan]","n房车"],
                        ["layout","I'lexaotl","n. 布局"],
                        ["format","['fo:mat]","n.格式"],
                        ["flooding","[fladm]","n泛滥"],
                        ["rural","['roaral]","ad. 乡下的"],
                        ["hard-working","[hard'w3:km]","ad. 刻苦的"],
                        ["torch","[to:tf]","n.火炬"],
                        ["sack","[sak]","V解雇n.麻袋"],
                        ["souvenirs","[su:va'niaz]","n. 纪念品"],
                        ["funnel","[fAnl]","n.漏斗"],
                        ["rendezvous","['rondivu:]","n.约定地点"],
                        ["vetting","[vetin]","n.审核"],
                        ["acknowledgement","[ak'nolidzmant]","n.鸣谢"],
                        ["wildlife","['warldlarf]","n.野生动物"],
                        ["meadow","'medaol","n草地"],
                        ["digestive","[dar'dzestiv]","ad. 消化的"],
                        ["fertiliser","['f3:talarza(r)]","n.肥料"],
                        ["fertilizer","['f3:talarza(r)]","n.肥料"],
                        ["rabbit","['rabit]","n.兔子"],
                        ["trash","[trael]","n.垃圾"],
                        ["nutrition","[njo'trifn]","n.营养"],
                        ["aging","['erdzin]","ad. 老化的"],
                        ["hothouse","['hothaos]","n.温室"],
                        ["habitat","['habitat]","n.栖息地"],
                        ["procedure","[pra pauzl]","n.程序"],
                        ["budget","['badzit]","n.预算"],
                        ["proposal","[pra'si:dza(r)]","n.提议"],
                        ["pavement","['pervmantl","n路面，人行道"],
                        ["restriction","[ri'strik{n]","n.限制"],
                        ["cookery","'kokarr]","n.烹饪"],
                        ["calorie","['kalan]","n. 卡路里"],
                        ["noticeable","['nautisabl]","ad.显著的"],
                        ["visibility","[, viza'bilati]","n.能见度"],
                        ["congestion","[kan'dzestfan]","n.拥塞"],
                        ["fume","[fju:m]","n.烟雾"],
                        ["modify","['modifar]","V 修改"],
                        ["fortune","['fo:tfuzn]","n.财富"],
                        ["reptile","['reptail]","n.爬行动物"],
                        ["territory","['teratri]","n.领士"],
                        ["monogamous","[ma'nogamas]","adj.一夫一妻制的"],
                        ["avoidance","[a'vordans]","n.回避"],
                        ["aspiration","[aspa'rer(n]","n.渴望"],
                        ["aerobic","[ea'raobik]","adi. 有氧的"],
                        ["expedition","[ekspa'din]","n.远足"],
                        ["maths","[ma0(s)]","n.数学"],
                        ["math","[ma0(s)]","n.数学"],
                        ["phonebook","[faunbok]","n.电话簿"],
                        ["supportive","[sa'po:tiv]","ad'. 支持的"],
                        ["fantastic","[fan'tastik]","ad.神奇的，极好的"],
                        ["destinations","[destr'ner{nz]","n.目的地"],
                        ["fascinating","['fœsmnertm]","ad. 迷人的"],
                        ["option","l'opfn]","n.选项"],
                        ["supplement","['saplumant]","n.补充"],
                        ["alternative","[ail't3:nativ]","ad. 替代的"],
                        ["parliament","I'pa:lamant]","n.议会"],
                        ["promenade","[.proma'na:d]","n.沿海步道"],
                        ["highlight","['harlaut","n.突出"],
                        ["medieval","[medr'i:vll","adi. 中世纪的"],
                        ["subcommittee","['sabkamiti]","n.小组委员会"],
                        ["overview","l'aovavju:]","n.概观"],
                        ["assortment","la'so:tmantl","n. 品种"],
                        ["boundary","I'baondri]","n边界"],
                        ["ramp","[rampl","n. 坡道，匝道"],
                        ["constant","['konstant]","adj.不变的"],
                        ["bend","[bend]","n.弯曲"],
                        ["stream","[stri:m]","n流"],
                        ["irrespective","[,irT'spektiv]","adi. 不管的"],
                        ["disastrous","[dr'za:stras)","adi.惨重的"],
                        ["tropical","['tropikl]","ad. 热带的"],
                        ["grateful","['grentfl]","ad. 感激的"],
                        ["rangers","['reindza(r)z]","n.护林员"],
                        ["measurement","['mezamant]","n.度量；测量"],
                        ["voluntary","['volantri]","ad. 志愿的"],
                        ["darkroom","I'da:kru:m]","n.暗室"],
                        ["reflective","[r'flektiv]","ad. 反馈的"],
                        ["portfolio","[past'fauliao]","n.资料"],
                        ["fireplaces","['faraplersiz]","n.𤩹炉"],
                        ["priority","[prar prati]","n.优先"],
                        ["verbalisation","['v3:balan, zerfn]","n.冗长"],
                        ["verbalization","['v3:balan, zerfn]","n.冗长"],
                        ["nest","[nest]","n.巢穴"],
                        ["evaporation","[r, veepa'rer(n]","n. 蒸发"],
                        ["hive","[harv]","n.蜂房"],
                        ["conservation","[konsa'ver{n]","n保护"],
                        ["networkers","[net'w3:ka(r)z]","n.网络人员"],
                        ["ecosystem","l'ickaosistam]","n.生态系统"],
                        ["flexibility","[,fleksa bilati]","n.灵活性"],
                        ["forestry","I'forIstri]","n. 林业"],
                        ["literature","['litratfa(r)]","n.文学"],
                        ["regulator","['reqjolerta(r)]","八.校准器"],
                        ["hammer","['hama(r)]","n.锤子"],
                        ["incubator","('inkjuberta(r)]","n.脬化器"],
                        ["workforce","['w3:kfo:s]","n.劳动力"],
                        ["attachment","[a'tat{mant]","n.附件"],
                        ["stable","['sterbl]","ad. 稳定的n.马圈"],
                        ["journal","['d33:nl]","n. 杂志"],
                        ["confidence","['konfidans]","n.信心"],
                        ["craftwork","['kra:ftw3:k]","n. 工艺品"],
                        ["internship","['int3:njip]","n. 实习"],
                        ["workload","l'w3:klaod]","n.工作量"],
                        ["appendices","[a'pendisi:z]","n.附件"],
                        ["parliament","['pa:lamant]","n.议院"],
                        ["recreational","[rekrr'erfanl]","ad. 休闲的"],
                        ["windmill","['windmil]","n.风车磨坊"],
                        ["mating","['mertin]","n.交配"],
                        ["fabric","['fæbrik]","n织物"],
                        ["cardiovascular","(,kasdiao'va:skjala(r)]","adi.心血管的"],
                        ["feasibility","[,fizzabilati]","n.可行性"],
                        ["evaluation","","n预估"],
                        ["collaborative","[ka'læbarativ]","adi. 合作的"],
                        ["simulation","[, simjo'ler(n]","n.仿真，模拟"],
                        ["coverage-lettering","['kAvard3'letarn]","n.新闻报道字体"],
                        ["precision","[pri'sizn]","n. 精密度"],
                        ["originality","la, ridza'nalatil","n.创意;独创性"],
                        ["objective","lab dzektiv]","ad. 客观的"],
                        ["nutrition","","n营养"],
                        ["pesticide","['pestisard]","n.杀虫剂"],
                        ["fuels","['fjuzals]","n燃料"],
                        ["weight","[wertl","n.重量"],
                        ["respondents","[ri'spondants]","n回复者"],
                        ["relevant","['relavant]","adi. 相关的"],
                        ["discipline","['disaplin]","n.学科，纪律"],
                        ["reliance","[rI'larans]","n依赖"],
                        ["ink","[uk]","n.墨水"],
                        ["tourists","['tuarrstsl","n游客"],
                        ["farming","I'faxmin]","n. 耕作"],
                        ["sample","['sa:mpl]","n样本"],
                        ["village","['vilid3]","n.村子"],
                        ["occupants","['okjapants]","n.居住者"],
                        ["certificate","[sa'tifikat]","n.证书"],
                        ["referee","[,refari:]","n.裁判"],
                        ["limitations","[,limr 'ter{nz]","n.限制"],
                        ["connectives","[ka'nektivz]","n.连接词"],
                        ["journalists","I'd33:nalists]","n.记者"],
                        ["publication","[pablr'kerfn]","n出版（物）"],
                        ["informality","[.info:'malatil","n非正式"],
                        ["informative","lin'fo:mativ]","ad. 告知的"],
                        ["ideal","[ar'dixal]","ad. 理想的"],
                        ["ascent","[a'sent]","n上升"],
                        ["summit","['samit]","n.山峰，首脑会议"],
                        ["package","['pakid3]","n包裹"],
                        ["firewood","['farawud]","n.柴火"],
                        ["stormy","['sto:mi]","ad.暴风兩的"],
                        ["proportion","(pra'po:jn]","n.比例"],
                        ["dimension","[dar men(n]","n.维度"],
                        ["upheaval","[Ap'hi:vl]","n剧变"],
                        ["adaptable","[a'daptabl]","ad.可适应的"],
                        ["evolutionary","L.i:va 'lu: (anri]","ad. 进化论的"],
                        ["cognitive","['kognativ]","ad. 认知"],
                        ["commitment","[ka'mitmant]","n.承诺"],
                        ["anatomy","[a'natami","n.解剖"],
                        ["counterpart","['kauntapa:t]","n对应部分"],
                        ["sensitive","['sensativ]","ad.敏感的"],
                        ["adaptation","[,adap'ter|n]","n适应"],
                        ["implication","[,implr'ker{n]","n含义"],
                        ["novice","['novIs]","n.新手"],
                        ["potential","[pa ten(I]","adi. 潜在的"],
                        ["annual","l'anjual]","ad. 每年的"],
                        ["dismissive","[dis mIsIv]","adi.轻蔑的"],
                        ["adaptability","la dapta'biliti]","n.适应性"],
                        ["pigeon","['pidzin]","n鸽子"],
                        ["specimen","['spesiman]","n标本"],
                        ["inclusion","[in'klu:zn]","n包含"],
                        ["hibernation","[harba'ner(n]","n.冬眠"],
                        ["hormone","['ho:maonl","n 激素，荷尔蒙"],
                        ["squirrel","['skwiral]","n.松鼠"],
                        ["satisfaction","[, satis'fak(n]","n满意度"],
                        ["chronological","[,krona'lodzikl]","ad. 按时间顺序的"],
                        ["distracting","[dr'straktin]","adi.分散注意的"],
                        ["semantic","[si'mantik]","ad. 语义的"],
                        ["episodic","[,epr'sodik]","ad. 情节的"],
                        ["strategy","['stratadzi]","n策略"],
                        ["procedure","(pra'si:dza(r)]","n.过程"],
                        ["diploma","[di'plaoma]","n.文凭"],
                        ["measurements","['mezamants]","n.测量"],
                        ["profile","l'praufarl]","n.个人简介"],
                        ["awful","L'a:fl]","ad. 可怕的"],
                        ["syndrome","['sindraom]","n综合征"],
                        ["quotations","[kwao'ter/nz]","n.报价单"],
                        ["poverty","I'povati","n. 贫穷"],
                        ["amusements","[a'mjuzzmants]","n.娱乐活动"],
                        ["justice","['dzastis]","n正义"],
                        ["heroine","T'herauml","n. 女主角"],
                        ["guardian","I'ga:dran]","n.监护人"],
                        ["debtors","['deta(r)z]","n债务人"],
                        ["traits","['treits]","n.特质"],
                        ["stereotypes","['sterratarps]","n.刻板印象"],
                        ["robust","[roo'bast]","ad.强大的"],
                        ["consensus","[kan' sensas]","n.共识"],
                        ["sibling","['siblm]","n.兄弟姐妹"],
                        ["nightmare","['nait, meal","n.噩梦"],
                        ["envious","['envias]","adi.嫉妒的"],
                        ["sociable","['saufabl]","ad.善于交际的"],
                        ["harsh","[ha:l]","ad. 严厉的"],
                        ["accurate","l'akjarat]","adi.准确的"],
                        ["status","['steitas]","n. 状态"],
                        ["processes","['praosasiz]","n.流程"],
                        ["rivalry","['raivlri]","n.对抗"],
                        ["annoying","[a'noun]","ad. 烦人的"],
                        ["refrigeration","[r, fridza'rer/n]","n. 冷藏"],
                        ["straw","[stro:]","n.稻草"],
                        ["sawdust","['so:dast]","n.锯末"],
                        ["pits","['pits]","n坑"],
                        ["components","[kam'paonants]","n. 组件"],
                        ["manufacturers","[manjo'faktfaraz]","n.厂商"],
                        ["chemicals","['kemiklz]","n.化学药品"],
                        ["competitors","[kam'petitaz]","n. 竞争者"],
                        ["coverage","I'kavaridz]","n.覆盖范围"],
                        ["graphics","['grafiks]","n.图形"],
                        ["visual","['vizoal]","adi'.视觉的"],
                        ["misleading","[mis'li:dm]","adi'.误导的"],
                        ["versions","['v3:{ans]","n.版本"],
                        ["controversy","[ kontrav3:SI]","n. 争议"],
                        ["ridiculous","[r dikjalas]","ad. 荒謬的"],
                        ["assumptions","[a'sampinz]","n.假设"],
                        ["editorials","[edi'to:rialz]","n.社论"],
                        ["emotional","[i'maofanl]","ad. 情感的"],
                        ["funding","I'fAndm]","n. 资金"],
                        ["code","[kaud]","n.密码"],
                        ["maximum","['maksimam]","ad. 最大的"],
                        ["coconut","['kaukanat]","n椰子"],
                        ["mould","[mauld]","n模具"],
                        ["machinery","[ma' fi:nart]","ad.机械化的"],
                        ["elastic","It'larstik]","ad.有弹性的"],
                        ["vertical","l'v3:tikl]","adi.垂直的"],
                        ["accountable","[a kauntabl]","ad. 有责任的"],
                        ["decisions","[dr'siznz]","n.决定"],
                        ["seasonal","['sizzanl]","ad'. 季节的"],
                        ["herds","[h3:dz]","n.群"],
                        ["clay","[klei]","n.士"],
                        ["eco-cement","l'i:kaost'ment]","n.生态水泥"],
                        ["nuts","[nAts]","n.坚果"],
                        ["arrows","l'arauz]","n.箭头"],
                        ["spears","[spra(r)z]","n.矛"],
                        ["concentrated","['konsntreitid]","adi.注意的"],
                        ["shipping","('Jipm]","n.运输"],
                        ["segments","['segmants]","n.部分"],
                        ["germs","[d33:mz]","n细菌"],
                        ["corn","[ko:n]","n.玉米"],
                        ["insects","['insekts]","n. 昆虫"],
                        ["coastline","['kaustlam]","n海岸线"],
                        ["critical","['kritikl]","adi.批判的 / 核心的"],
                        ["cognition","[kog'nijn]","n.认识"],
                        ["emotion","Ir'mau(n]","n.感情"],
                        ["intelligence","lin'telidzans]","n. 情报 /智力"],
                        ["connected","[ka'nektid]","ad. 连接的"],
                        ["self-centred","[self'senta(r)d]","ad. 自我的"],
                        ["passive","['pasiv]","ad. 消极的/ 被动的"],
                        ["stimulation","[,stimjo'ler/fn]","n.刺激，鼓励"],
                        ["lid","[lid]","n.盖子"],
                        ["gravity","['gravati]","n重力"],
                        ["Istems","[stemz]","n茎"],
                        ["obstacles","L'obstakls]","n.困难"],
                        ["mechanism","['mekanizam]","n.进程/机械装置"],
                        ["seminar","['semina:(r)]","n.研讨会"],
                        ["drought","[draot]","n.千旱"],
                        ["erosion","[t'rauzn]","n腐蚀"],
                        ["digestion","[dar'dzestfan]","n.消化"],
                        ["furniture","['f3:nitfa(r)]","n.家具"],
                        ["retail","['ri:terl]","n零售"],
                        ["maturitv","[ma'tfvarati]","n.成熟"],
                        ["postal","['paustl]","ad. 邮政的"],
                        ["self-evaluation","[selfi, valjo'er/n]","n.自我评估"],
                        ["random","['randam]","ad. 随机的"],
                        ["cost-effective","['kosti'fektiv]","ad.性价比高的"],
                        ["navigate","['navigert]","八航行"],
                        ["genetic","[dza'netik]","ad.基因的"],
                        ["density","['densatil","n.密度"],
                        ["triangle","['trarangl]","n三角"],
                        ["cliffs","[klifs]","n. 悬崖"],
                        ["comprehension","[,komprr'hen(n]","n.理解"],
                        ["format","['fo:mat]","n.格式"],
                        ["irrigation","[,iri'getfn]","n.灌溉"],
                        ["contaminants","Ikan'taminants]","n.污染物"],
                        ["soldiers","['sauldza(r)z]","n士兵"],
                        ["concrete","['konkrist]","n.混凝士"],
                        ["lifespan","['larfspan]","n. 寿命"],
                        ["therapy","['Oerapi]","n.疗法；理疗"],
                        ["temperature","['tempratfa(r)]","n.温度"],
                        ["fluids","['fluzidz]","n.液体"],
                        ["kidney","['kidnt]","n肾"],
                        ["sustainable","[sa'steinabl]","ad.可忍受的"],
                        ["portable","['po:tabl]","ad. 便携的"],
                        ["excitement","[ik'santmant]","n.激动"],
                        ["mammal","I'maml","n.哺乳动物"],
                        ["breathe","[bri:ö]","V呼吸"],
                        ["pollutants","[pa lustants]","n.污染物"],
                        ["quidelines","['gardlamz]","n.方针政策"],
                        ["mapping","['mapin]","n制图"],
                        ["calculator","['kalkjolerta(r)]","n.计算器"],
                        ["perfumes","['p3:fju:mz]","n.香水"],
                        ["exploration","[,ekspla'reifn]","n.探索"],
                        ["toothache","I'tu:0erk]","n. 牙痛"],
                        ["pirates","['pararats]","n海盗"],
                        ["powder","['paoda(r)]","n粉"],
                        ["cosmetics","[koz'metiks]","n.化妆品"],
                        ["carpets","['ka:pits]","n地毯"],
                        ["tunnel","['tanl]","n隧道"],
                        ["packaging","['pakid3in]","n.打包"],
                        ["worms","[w3:mz]","n.虫子"],
                        ["odour=odor","L'asda(r)]","n气味"],
                        ["butterflies","['bataflaiz]","n蝴蝶"],
                        ["bacteria","[beek'tiarial","n.细菌"],
                        ["protein","['pravtixn]","n蛋白质"],
                        ["migration","[mar'gretfn]","n.迁徙"],
                        ["morality","[ma'ralati]","n.道德"],
                        ["situational","[,sitfo'er/nl]","ad.环境造成的"],
                        ["aspirations","[aspa'rerfnz]","n.渴望"],
                        ["amber","['amba(r)]","n.琥珀"],
                        ["tolerance","['tolarans]","n.容忍"],
                        ["contribution","[kontri'bju:jn]","n.贡献"],
                        ["humidity","[hju:' midati]","n.潮湿度"],
                        ["barrier","['barra(r)]","n.阻碍"],
                        ["tuna","['tju:na]","n.金枪鱼"],
                        ["gill","[gil]","n.鳃"],
                        ["cables","['kerbls]","n.电缆"],
                        ["oyster","L'arsta(r)]","n牡蛎"],
                        ["guessing","['gesmn]","n.推测"],
                        ["relaxation","[,ri:lak'serfn]","n.放松"],
                        ["concentration","[.konsn'trer/n]","n.注意力"],
                        ["literacy","['litarast]","n.读写能力"],
                        ["predators","['predata(r)z]","n.捕食者"],
                        ["molt","['mault]","n.脱毛"],
                        ["diversity","[dar'v3:sati","n.多样性"],
                        ["cement","[sI'ment]","n. 水泥"],
                        ["cognitive","['kognativ]","ad.认知的"],
                        ["peers","[pra(r)z]","n.同龄人"],
                        ["rational","['ræfnal]","adi.理性的"],
                        ["willing","['wilin]","ad.意愿的"],
                        ["instinct","['instukt]","n.天性/本能"],
                        ["reward","[rt'wa:d]","n.报酬"],
                        ["boiler","['barla(r)]","口.水壶"],
                        ["monument","['monjumant]","n.纪念堂"],
                        ["drawback","I'dra:bak]","n缺点"],
                        ["obligation","[,pbli'get/n]","n.义务"],
                        ["responsibility","[r, sponsa'bilati]","n. 责任"],
                        ["rags","[ragz]","n.破布"],
                        ["rainbow","['rembaul","n.彩虹"],
                        ["desert","['dezat]","n沙漠"],
                        ["lizard","['lizad]","n.蜥蜴"],
                        ["institution","[unstr'tju:(n]","n.机构"],
                        ["authority","[a: 'Oprati]","n.权威"],
                        ["shrimps","[frimps]","口虾"],
                        ["moisture","['marstfa(r)]","n.潮湿"],
                        ["ultraviolet","LAltra'varalat]","n.紫外线"],
                        ["bubble","['babl]","n.气泡"],
                        ["passion","['pa(n]","n.激情"],
                        ["responsible","[ri'sponsabl]","ad. 负贵的"],
                        ["landmarks","l'landma:ks]","n.路标"],
                        ["robots","['raobots]","n.机器人"],
                        ["psychology","[sar'koladzi]","n.心理学"],
                        ["varied","I'vearid]","ad. 变化的"],
                        ["planet","['plant]","n星球"],
                        ["ethnics","['eOnrks]","n.人种学；少数民族"],
                        ["nomad","['naomad]","n游牧民族"],
                        ["eggplant","L'egpla:nt]","n.茄子"],
                        ["camel","['kaml]","n.骆驼"],
                        ["slaves","[sleivz]","n. 奴隶"],
                        ["vegetation","[,vedza'terfn]","n.植被"],
                        ["lighting","['lartin]","n.灯光"],
                        ["fossil","I'fosl]","n.化石"],
                        ["grocery","I'grausari]","n.杂货店"],
                        ["numerous","['njurmaras]","n.很多的"],
                        ["repellent","[rI'pelant]","ad. 排斥的 n.驱虫剂"],
                        ["odd","[od]","adi. 古怪的"],
                        ["factual","['fakt{val]","ad. 事实的"],
                        ["purole","['p3ipl]","n紫色"],
                        ["consolidation","[kan,solr'derfn]","n.巩固"],
                        ["conscious","['konfas]","adi.有意识的"],
                        ["auditory","l'o:datri]","ad. 听觉"],
                        ["symptom","['sumptom]","n.症状"],
                        ["medication","[,medr 'ker{n]","n药物治疗"],
                        ["intimate","l'intumat]","adi. 亲密的"],
                        ["nightmare","I'nartmea(r)]","n 噩梦"],
                        ["teaspoon","['ticspu:n]","n.茶匙"],
                        ["beetroot","['bistrust]","n.甜菜根"],
                        ["retrieval","Irr'tri:vl","n检索"],
                        ["prompt","[prompt]","v/n. 促使，激励 ad.迅速的，敏捷的"],
                        ["impairment","[im'peamant]","n损害"],
                        ["autism","L'artizaml","n.自闭症"],
                        ["autistic","[o:'tistrk]","ad. 患自闭症的"],
                        ["textile","I'tekstarl]","n.纺织品；纺织"],
                        ["long-lasting","[lon'la:stin]","ad.持久的"],
                        ["poisonous","['poizanas]","ad.有毒的"],
                        ["medal","I'medi]","n.奖章"],
                        ["additive","L'adativ]","n.添加剂"],
                        ["ingredient","[in'gri:diant]","n.成分"],
                        ["consumer","(kan'sju:ma(r)]","n.消费者"],
                        ["colony","['kolan]","n.殖民地"],
                        ["cultivation","[kAltr'ver{n]","n.栽培"],
                        ["consumption","[kan'samp/n]","n.消费"],
                        ["accept","[ak'sept]","V接受"],
                        ["emotions","[i'mao(nz]","八.情绪"],
                        ["purpose","l'p3:pas]","n.目的"],
                        ["corn","[ko:n]","n. 玉米"],
                        ["rivals","T'rarvls]","n. 竞争对手"],
                        ["complex","['kompleks]","ad.复杂的"],
                        ["segments","['segmants]","n段"],
                        ["timber","['timba(r)]","n.木材"],
                        ["sustainable","[sa'sternabl]","ad. 可持续发展的"],
                        ["fertiliser","['f3:talatza(r)]","n.肥料"],
                        ["fertilizer","['f3:talatza(r)]","n.肥料"],
                        ["rabbit","['rabit","n.兔子"],
                        ["microscope","I'markraskaupl","n.显微镜"],
                        ["nutrition","Injo'trifn]","n.营养"],
                        ["flavour=flavor","['flerva(r)]","n.味道"],
                        ["drugs","[dragz]","n药物"],
                        ["whistle","L'wisl","V吹口哨"],
                        ["instinctive","[un'stuktiv]","ad.本能的"],
                        ["critical","['kritikl]","ad. 至关重要的"],
                        ["preserved","[pri'z3:vd]","adi. 保存的"],
                        ["poet","['paort]","n.诗人"],
                        ["antibiotic","[,antibar'otik]","n.抗生素"],
                        ["varied","['vearid]","adi. 多种多样的"],
                        ["wildlife","['waildlarf]","n.野生动物"],
                        ["landmark","I'lændma:k]","n.地标"],
                        ["moisture","['moistfa(r)]","n水分，潮湿"],
                        ["chemicals","['kemikls]","n.化学品"],
                        ["concentrated","['konsntrettid]","adi.集中的"],
                        ["restrained","[rr' streind]","ad. 克制的"],
                        ["documentation","[,dokjomen'ter(n]","n.文档"],
                        ["tutorials","Itju: to:rals]","n.教程"],
                        ["reflective","[ri'flektiv]","adi.反射的"],
                        ["journalism","['d33:nalizam]","n.新闻"],
                        ["depth","[depo]","n.深度"],
                        ["remember","[rI'memba(r)]","V记得"],
                        ["navigational","I, navi'gerfanl]","ad.航行的"],
                        ["signature","['signatf@(r)]","n.签名"],
                        ["evolution","[i:va'lu:{n]","n.进化"],
                        ["mapping","['mapm]","n. 映射"],
                        ["commerce","['kom3:s]","n.商业"],
                        ["standard","['standad]","adi./n. 标准（的）"],
                        ["Greek","[grik]","n.希腊人"],
                        ["dominant","I'dommantl","ad. 占主导地位的"],
                        ["mixture","['mikstfa(r)]","n.混合物"],
                        ["cosmetics","[koz'metiks]","n.化妆品"],
                        ["hospitality","[,hospi'talati]","n.好客"],
                        ["symbols","['simbls]","n.符号"],
                        ["flavours","['flerva(r)zl","n.口味"],
                        ["flavors","['flerva(r)zl","n.口味"],
                        ["enlargement","[in lardzmant]","n.扩大"],
                        ["critics","['kritrks]","n.评论家"],
                        ["protected","[pra'tektid]","adi. 受保护的"],
                        ["infection","[in'fek{n]","n.感染"],
                        ["stimulate","['stumjolent]","V刺激"],
                        ["description","[dr'skrip/n]","n.描述"],
                        ["lonely","l'laonli]","ad.孤独的"],
                        ["industrial","[i'dastrial]","adi. 工业的"],
                        ["trumpet","['trampit]","n.小号"],
                        ["receiver","[rr'si:va(r)]","n.接收机"],
                        ["magnet","['magnat]","n.磁铁"],
                        ["pottery","['potari]","n.陶器"],
                        ["lions","Maranzl","n狮子"],
                        ["emperor","['empara(r)]","n皇帝"],
                        ["feathers","['feda(r)z]","n.羽毛"],
                        ["perfumes","['p3:fjurmz]","n.香水"],
                        ["wealth","[well]","八.财富"],
                        ["taxes","[taksis]","n税"],
                        ["saliva","[sa larval","n.唾液，口水"],
                        ["cleanliness","['klenlinas]","n清洁度"],
                        ["excavation","[,ekska'ver/n]","n.挖掘"],
                        ["pumice","['pAmis]","n浮石"],
                        ["luxurious","[lag'zuarras]","adi.豪华的"],
                        ["physician","[fi'zi/n]","n.医师"],
                        ["unsanitary","Inn' sanatrrl","ad. 不卫生的"],
                        ["outbreaks","l'aotbrerks]","n.爆发"],
                        ["craft","[kra:ft]","n工艺"],
                        ["associations","[a saufl'erfnz]","n协会"],
                        ["commercial","[ka'm3:fl]","adi. 商业的"],
                        ["chemist","['kemist]","n.化学家"],
                        ["acid","['asid]","n.酸"],
                        ["shelter","('felta(r)]","n.避难所"],
                        ["nectar","['nekta(r)]","n.花蜜"],
                        ["disinfectant","[, disin'fektant]","n.消毒剂"],
                        ["ecologist","('koladzist]","n.生态学家"],
                        ["vegetation","[, vedza ter/n]","n.植被"],
                        ["composition","[,kompa'z1(n]","n. 组成"],
                        ["nutrients","['nju:triants]","n.营养素"],
                        ["indigenous","lin'didzanas]","ad.原住的"],
                        ["tropical","['tropikl]","ad. 热带的"],
                        ["ecosystem","L'ikausrstaml","n. 生态系统"],
                        ["dense","[dens]","ad. 茂密的"],
                        ["ideal","[ar'disal]","adi.理想的"],
                        ["session","['se(in]","n.会议"],
                        ["quantity","['kwontati]","n.数量"],
                        ["indication","[indr'ker(n]","n.指示"],
                        ["watermills","I'wo:tamulz]","n.水车"],
                        ["windmills","['windmilz]","n.风车"],
                        ["textiles","['tekstaulz]","n.纺织品"],
                        ["fabrics","['fabriks]","n.面料"],
                        ["lace","[lers]","n.花边"],
                        ["ribbons","['ribanz]","n 色带，缎带"],
                        ["enormous","[r'no:mas]","ad.巨大的"],
                        ["carts","[ka:ts]","n.购物车"],
                        ["numerous","['nju:maras]","ad.众多的"],
                        ["canals","[ka'nalz]","n运河"],
                        ["knowledgeable","I'nolidzabl]","ad. 知识渊博的"],
                        ["retailing","['ri:terlin]","n.零售业"],
                        ["entrepreneurs","[ontrapra'n3»z]","n. 企业家"],
                        ["visibility","[, viza 'bilati]","n.能见度"],
                        ["potential","[pa'ten(1]","adi. 潜在的"],
                        ["explosion","lik'splaozn]","口爆炸"],
                        ["necessities","[nt'sesitus]","n必需品"],
                        ["unimaginable","[,Ani'madzinabl]","ad.难以想象的"],
                        ["arid","l'ard]","n.千旱"],
                        ["charcoal","['ta:kaul]","n. 木炭"],
                        ["irrigation","[,irr' getfn]","n.灌溉"],
                        ["dependable","[di'pendabl]","ad'.可靠的"],
                        ["livestock","M'larvstokl","n. 家畜"],
                        ["notable","['naotabl]","ad. 值得注意的"],
                        ["cereals","['siarralz]","n. 谷物"],
                        ["preservation","[,preza ver(n]","n.保存"],
                        ["additional","[a'difanl]","ad.额外的"],
                        ["initiative","[r'nifativ]","n.主动权ad主动的"],
                        ["protein","['pravti:n]","n. 蛋白"],
                        ["original","[a ridzanl]","ad. 原版的"],
                        ["proposal","[pra'pauzl","n提案"],
                        ["colony","['kolan]","n.群落，殖民地"],
                        ["phase","[ferz]","n（电的）相，阶段"],
                        ["medication","[, medi ker|n]","n药物，制剂"],
                        ["companionship","[kam'panianJip]","n情谊，友谊"],
                        ["cement","Isr'mentl","n.水泥"],
                        ["spray","[sprei]","n.喷剂"],
                        ["evaporation","Ir,vaepa'rerfn]","n.蒸发"],
                        ["evaporation","Ir,vaepa'rerfn]","n.蒸发"],
                        ["stability","[stabilati]","n稳定"],
                        ["calculation","[,kalkjo'ler/n]","n 计算"],
                        ["eclipse","[r'klips]","n.日食，月食"],
                        ["rumour","['ruxmal","n.谣言"],
                        ["rumor","['ruxmal","n.谣言"],
                        ["frustration","[frA'strerfn]","n.挫折"],
                        ["claw","[klo:]","n.爪子"],
                        ["cushion","['kufn]","n.靠垫"],
                        ["damp","[dæmpl","ad. 潮湿阴暗的"],
                        ["mobility","[mao' bilati]","n.活动性"],
                        ["durable","['divarabl]","ad'.持久的，耐用的"],
                        ["pharmacy","['farmasrl","n.药店"],
                        ["manufacturing","[, manjo faktform]","ad. 制造的"],
                        ["mechanism","I'mekanizaml","n.机制"],
                        ["pharmacy","['farmast]","n.药房"],
                        ["inscription","fin'skripfn]","n刻宇，铭文"],
                        ["judo","[dzu:dao]","n.柔道"],
                        ["apron","l'erpran]","n.围裙"],
                        ["automotive","La:ta'maotiv]","ad.汽车的"],
                        ["courtyard","['ko:tja:d]","n.庭院"],
                        ["introductory","[, intra'dAktari]","ad. 介绍的"],
                        ["rationale","[,rafa'na:l]","n. 基本原理，根本原因"],
                        ["evaluative","Ir'valivativ","adj评价的，估值的"],
                        ["hawk","[haik]","n.鹰"],
                        ["portrait","['pa:trent]","n.肖像"],
                        ["virtuous","['vaitfuas]","adi. 道德高尚的"],
                        ["cognitive","['kognativ]","ad.感知的，认知的"],
                        ["obstacle","['obstakl]","n.障碍"],
                        ["relevance","['relavans]","n. 相关性"],
                        ["album","['albam]","n.相册"],
                        ["fragile","['fradzail]","ad脆弱的，易碎的"],
                        ["catering","['keitorm]","n.餐饮"],
                        ["dissatisfaction","I,dis, satrs'fak(n]","n.不满意"],
                        ["controversial","[,kontra'v3: (l]","ad.有争议的"],
                        ["faulty","['fo:lti]","ad. 错误的"],
                        ["procedure","(pra'si:dza(r)]","口.程序"],
                        ["ethical","l'eOrkl]","adj. 伦理的，道德的"],
                        ["correlation","[,kora'ler{n]","n.联系，相关"],
                        ["hormone","['ho:maun]","n. 激素，荷尔蒙"],
                        ["accessible","lak'sesabl]","ad. 可接近的"],
                        ["sandal","['sandl]","n.凉鞋"],
                        ["horticulture","['ha:tikAltfa(r)]","n.园艺学，园艺"],
                        ["sector","['sekta(r)]","n.部门"],
                        ["artificial","[,a:tr'fr/l]","ad'. 人工的"],
                        ["sweetener","['swi:tna(r)]","n.甜味剂"],
                        ["obesity","[as'bissatt]","n.肥胖"],
                        ["knitting","['nitm]","n.编织"],
                        ["maintenance","['meuntanans]","n.维持，维修"],
                        ["pedestrian","[pa'destrian]","n.行人"],
                        ["pavilion","[pa'vilian]","n 亭子"],
                        ["scheme","[ski:ml","n. 方案"],
                        ["congestion","[kan'dzestfan]","n.拥挤"],
                        ["affordable","[a fo:dabl]","ad. 支付得起的"],
                        ["skeleton","['skelitn]","n. 骨架"],
                        ["animation","[,ani'mer|n]","n.动画，动画片"],
                        ["apprenticeship","[a prentifip]","n.学徒期"],
                        ["machinery","Ima' fi:nari","n.机器，机械"],
                        ["refurbishment","[,ri:'f3:br|mant]","n翻新，整修"],
                        ["texture","['tekstfa(r)]","n. 质地，质感"],
                        ["evolution","L,irva'lu:{n]","n.进化"],
                        ["kingfisher","['kinfifa(r)]","n.翠鸟"],
                        ["scary","['skeari]","adi. 吓人的"],
                        ["meditation","I, medi'ter{n]","n.冥想"],
                        ["jealousy","['dzelasi]","n妒忌"],
                        ["initiation","[.nifterfn]","n. 入门，初学"],
                        ["ardent","l'a:dnt]","ad.热烈的，激情的"],
                        ["capitalism","['kæpitalizam]","n. 资本主义"],
                        ["inspiration","[,unspa'ret/n]","n.灵感"],
                        ["profound","Ipra'faond]","ad.强烈的，极度的，深刻的"],
                        ["depression","[dr'prefn]","n. 忧郁，沮丧"],
                        ["resilience","Irr'zilians]","n.弹性，复原能力"],
                        ["attic","L'aetik]","n阁楼"],
                        ["cardboard","['ka:dboid]","n.纸板"],
                        ["nucleus","['nju:klias]","n.核"],
                        ["cuisine","[kwr'zi:n]","n.饮食"],
                        ["coincidence","[kao' insidans]","n.巧合"],
                        ["methodology","I, meta'dolad3i]","n.方法论"],
                        ["correlation","[,kora'lerfn]","n联系，相关"],
                        ["variable","I'vearrabl]","n. 变量"],
                        ["adolescent","[,ada'lesnt]","n.lad.青少年（的）"],
                        ["enormous","Ir'no:masl","ad. 大量的"],
                        ["barrier","['berra(r)]","n障碍"],
                        ["intense","[in'tens]","ad.强烈的"],
                        ["collaboration","[ka laba'rer(n]","n.合作"],
                        ["nutrition","Inju'trrfn]","n.营养"],
                        ["maternity","[ma't3rnati]","n.母亲身份"],
                        ["tractor","['trakta(r)]","n.拖拉机"],
                        ["packet","['pakit]","n.小包，小盒子；包装"],
                        ["modification","[,modifi'kerfn]","n改变，修改"],
                        ["garment","['ga:mant]","n.服装"],
                        ["hardship","['ha:djip]","n.艰难"],
                        ["linen","['linin]","n.亚麻，床单"],
                        ["hemp","[hemp]","n.麻类植物"],
                        ["dominance","['dominans]","n.主导，占优势"],
                        ["herb","[h3:b]","n.草药"],
                        ["patio","['patrau]","n.院子，天井，平台"],
                        ["agenda","[a'dzenda]","n.议事日程"],
                        ["rumour=rumor","['ru:ma]","n.谣言"],
                        ["pavement","I'pervmant]","n. 人行道"],
                        ["fume","[fju:m]","n.烟雾，气"],
                        ["railing","I'reilmnl","n.栏杆"],
                        ["ramp","[rempl","n.坡道，斜坡"],
                        ["emission","Ir'mi(n]","n.排放，散发"],
                        ["extinction","[ik'stinkfn]","n.灭绝"],
                        ["spice","[spars]","n. 香料"],
                        ["voyage","['vond3]","n航海，航行"],
                        ["colony","I'kolant]","n.殖民地"],
                        ["vegetation","[, vedza ter/n]","n.植被"]
                        )
                return words
        def bookWordsSecond(slef):
                words = (
                        ["date of birth","生日",""],
                        ["type of insurance","保险类型",""],
                        ["snow boarding","滑雪板",""],
                        ["planning meeting","计划会议",""],
                        ["outdoor activities","户外活动",""],
                        ["joining fees","加盟费",""],
                        ["leisure centre","休闲中心",""],
                        ["bunch of flowers","花束",""],
                        ["delivery fee","快递费用",""],
                        ["high seasons","旺季",""],
                        ["peaceful environment","和平环境",""],
                        ["existing skills","现有技能",""],
                        ["investment schemes","投资计划",""],
                        ["house insurance","房屋保险",""],
                        ["client engineer","客户维护工程师",""],
                        ["horse riding","骑马",""],
                        ["hot chocolate","热巧克力",""],
                        ["warm clothing","保暖服",""],
                        ["toy factory","玩具厂",""],
                        ["petrol station","加油站",""],
                        ["employment medical","就业医疗",""],
                        ["certificate","证明",""],
                        ["sports injury","运动伤害",""],
                        ["space museum","太空博物馆",""],
                        ["personal attention","个人注意力",""],
                        ["internet cafe","网吧",""],
                        ["fish tank","鱼缸",""],
                        ["membership limitation","会员限制",""],
                        ["drama workshop","戏剧社",""],
                        ["group deposit","团体押金",""],
                        ["dance classes","舞蹈班",""],
                        ["round tables","圆桌",""],
                        ["total deposit","整体押金",""],
                        ["special items","特别项目",""],
                        ["country living","乡村生活",""],
                        ["eating out","外出就餐",""],
                        ["house agent","房屋中介",""],
                        ["branch manager","部门经理",""],
                        ["side entrance","侧门",""],
                        ["side gate","侧门",""],
                        ["post office","邮局",""],
                        ["office furniture","办公家具",""],
                        ["advanced lessons","高级课程",""],
                        ["free entry","免门票",""],
                        ["large slide","大滑梯",""],
                        ["evening appointment","晚间约会(商务/正式）",""],
                        ["regular check","例行检查",""],
                        ["heart disease","心脏病",""],
                        ["sun cream","防晒霜",""],
                        ["paddling pool","戏水池",""],
                        ["central heating","中央供暖",""],
                        ["book reservation","图书典藏",""],
                        ["cable car","缆车",""],
                        ["baseball coach","棒球教练",""],
                        ["rock pool","潮汐潭",""],
                        ["town hall","市政大厅",""],
                        ["ice pack","冰袋",""],
                        ["order section","订单管理部",""],
                        ["advanced level","高级水平",""],
                        ["washing staff","裁员/洗衣工",""],
                        ["evening meals","晚餐",""],
                        ["old-fashioned exterior","过时的外表",""],
                        ["name cards","名片",""],
                        ["private company","私人企业",""],
                        ["family photo","家庭照片",""],
                        ["driving licence","驾照",""],
                        ["type of magazine","杂志体裁",""],
                        ["calling diversion","呼叫转移",""],
                        ["current address","当前住址",""],
                        ["nursery supervisor","幼儿园管理员",""],
                        ["film festival","电影节",""],
                        ["back row","后排",""],
                        ["furniture designers","家具设计师",""],
                        ["preferred occupation","首选职业",""],
                        ["previous working","先前工作",""],
                        ["experience","经验",""],
                        ["bank statement","银行账单",""],
                        ["daytime temperature","日间温度",""],
                        ["outdoor swimming pool","露天泳池",""],
                        ["coral reef","珊瑚礁",""],
                        ["maintenance of gardens","花园维护",""],
                        ["good value","实惠",""],
                        ["alarm system","警报系统",""],
                        ["walking boots","登山靴",""],
                        ["book keeper","记账员",""],
                        ["home welcome","宾至如归；家庭欢迎",""],
                        ["health service","健康服务",""],
                        ["limited parking","停车限制",""],
                        ["service manager","服务部经理",""],
                        ["silver package","银色包裹",""],
                        ["energy saving","节能",""],
                        ["job title","职位名称",""],
                        ["starting salary","起薪",""],
                        ["renew passport","更新护照",""],
                        ["flower shop","花店",""],
                        ["gold stars","金星",""],
                        ["special requirement","特殊需求",""],
                        ["dark trousers","深色裤子",""],
                        ["monthly rent","月租金",""],
                        ["previous major","原专业",""],
                        ["decoration balloons","装饰气球",""],
                        ["vegetable burger","蔬菜汉堡包",""],
                        ["return tickets","回程票",""],
                        ["customer service officer 24H","客服经理",""],
                        ["sleeping bag","睡袋",""],
                        ["washing machine","洗衣机",""],
                        ["group trip","团队出游",""],
                        ["non-smoking room","禁烟室",""],
                        ["dreamtime under stars","夜晩畅想",""],
                        ["long stick","长棍子",""],
                        ["weekly return","周回托",""],
                        ["bank transfer","银行转账",""],
                        ["required date","规定时间",""],
                        ["bills and meals","账单和餐",""],
                        ["roadrunners","走鹃",""],
                        ["current occupation","当前工作",""],
                        ["type of accommodation","住宿类型",""],
                        ["starting date","起始日期",""],
                        ["estimated value","估价",""],
                        ["safety check","安全检查",""],
                        ["flight service","空中服务",""],
                        ["maximum price","最高价格",""],
                        ["membership number","会员号码",""],
                        ["sports equipment","体育装备",""],
                        ["fresh products","新鲜产品",""],
                        ["cycling route","骑行路线",""],
                        ["group discount","团购优惠",""],
                        ["safety regulations","安全守则",""],
                        ["error message","错误信息",""],
                        ["garden room","花房",""],
                        ["isolated spot","隔离点",""],
                        ["car number","车牌号",""],
                        ["self drive","自驾",""],
                        ["culture centre","文化中心",""],
                        ["modern authors","现代作家",""],
                        ["free parking","免费停车",""],
                        ["extra room","额外房间",""],
                        ["short time","短时间",""],
                        ["accommodation type","住宿类型",""],
                        ["sports centre","运动中心",""],
                        ["job requirement","工作需要",""],
                        ["length of stay","逗留时间",""],
                        ["Spring Park","（公园名称）",""],
                        ["reference number","参考号码",""],
                        ["family use","家用",""],
                        ["preferred equipment","偏爱的装备",""],
                        ["off-peak time","非高峰时间",""],
                        ["helicopter trip","直升机游览",""],
                        ["organic food","有机食物",""],
                        ["poor quality","低质量",""],
                        ["organic farming","有机农业",""],
                        ["language skill","语言技能",""],
                        ["night flight","夜航",""],
                        ["white mountain","白雪覆盖的山",""],
                        ["golf court","高尔夫球场",""],
                        ["friendly faces","和善的面孔",""],
                        ["grocery stores","杂货铺",""],
                        ["juice bottles","果汁瓶",""],
                        ["protection policy","保护政策",""],
                        ["sick pay","病假工资",""],
                        ["leather shoes","皮鞋",""],
                        ["teaching venue","授课地点",""],
                        ["vegetarian food","素食",""],
                        ["new opera","新戏剧",""],
                        ["Top Mount","冷冷冻室上置型（冰箱）",""],
                        ["on the rack","在架子上",""],
                        ["leather jacket","皮夹克",""],
                        ["public outskirts","公共郊区",""],
                        ["International Express","（公司名称）",""],
                        ["lost mails","丟失的邮件",""],
                        ["student discount","学生折扣",""],
                        ["comfortable shoes","舒服的鞋",""],
                        ["value of money","钱的价值",""],
                        ["length of waiting","等待时间",""],
                        ["free recipe","免费配方",""],
                        ["conference centre","会议中心",""],
                        ["dust bag","垃圾袋",""],
                        ["rock climbing","攀岩",""],
                        ["no nuts","不要坚果",""],
                        ["egg cartons","装蛋盒",""],
                        ["electricity supply","电力供应",""],
                        ["group booking discount","团购优惠",""],
                        ["van driver","厢式货车司机",""],
                        ["advertising company","广告公司",""],
                        ["total payment","总总费用",""],
                        ["different performers","不同的表演者",""],
                        ["fridge model","冰箱型号",""],
                        ["financial loss","金融损失",""],
                        ["long strap","长带子",""],
                        ["total value","总价值",""],
                        ["customer service","顾客服务",""],
                        ["postal fee","邮费",""],
                        ["ID code numbers","身份代码",""],
                        ["leather shoes","皮鞋",""],
                        ["daytime class","白天课程",""],
                        ["in transit","转机中",""],
                        ["electronic game centre","电玩中心",""],
                        ["Asian cooking class","亚洲厨师班",""],
                        ["business companies","商业公司",""],
                        ["inconvenient location","不方便的位置",""],
                        ["good performance","好的表现",""],
                        ["vocal class","声乐班",""],
                        ["personal tutor","私人老师；个人辅导老师;个人导师",""],
                        ["coastal roads","沿海公路",""],
                        ["extra transportation cost","额外的输成本",""],
                        ["baseball coach","棒球教练",""],
                        ["central heating","中央供暖",""],
                        ["child seat","儿童座椅",""],
                        ["temporary staff","临时雇员",""],
                        ["agency representatives","代理商代表",""],
                        ["computer literate","精通计算机",""],
                        ["season ticket","季票",""],
                        ["basic package","基本套餐(话费等)",""],
                        ["public show","公开表演",""],
                        ["course fee","课程费用",""],
                        ["ozone layer","臭氧层",""],
                        ["changing room","更衣室",""],
                        ["personal use","个人使用",""],
                        ["side gate","侧门",""],
                        ["green ride","绿色骑行",""],
                        ["job agency","职业介绍所",""],
                        ["registration process","注册过程",""],
                        ["interpersonal skills","人际交往能力",""],
                        ["customer service","客户服务",""],
                        ["road runner","跑步者",""],
                        ["solar pump","太阳能泵",""],
                        ["visitor centre","访客中心",""],
                        ["unaccompanied children","无人陪伴儿童",""],
                        ["racing car","赛车",""],
                        ["urban garden","城市公园",""],
                        ["special feature","特点",""],
                        ["under-age children","未适龄儿童",""],
                        ["comment card","意见卡",""],
                        ["booking form","预订表格",""],
                        ["room services","客房服务",""],
                        ["music video","音乐视频",""],
                        ["traffic noise","交通噪声",""],
                        ["oil painting","油画",""],
                        ["postal items","邮政物件",""],
                        ["live music","现场音乐",""],
                        ["craft fair","手工艺品集市",""],
                        ["exhibitor entrance","展览者入口",""],
                        ["academic record","学术记录",""],
                        ["local artists","当地艺术家",""],
                        ["traffic jam","堵车",""],
                        ["calling fee","电话费",""],
                        ["express trains","高速列车",""],
                        ["self-cafeteria","自助餐厅",""],
                        ["European painting","欧洲画作",""],
                        ["historical photograph","历史照片",""],
                        ["coffee shop","咖啡店",""],
                        ["garden pots","洒水壶；花园罐子",""],
                        ["professional knowledge","专业知识",""],
                        ["education facilities","教育设施",""],
                        ["check number","核对数目",""],
                        ["unappealing appearance","无吸引力的外表",""],
                        ["cabin keys","(船）客舱钥匙",""],
                        ["after formality","寒暄后",""],
                        ["camera man","摄像师",""],
                        ["sculpture garden","雕塑花园",""],
                        ["quarantine service","检疫服务",""],
                        ["plant seeds","植物种子",""],
                        ["meeting point","碰头地点",""],
                        ["fringe stage","额外展台",""],
                        ["arm badge","袖标，手环",""],
                        ["class representative","班级代表",""],
                        ["river taxi","摆渡船",""],
                        ["traffic lights","交通灯",""],
                        ["computer breakdown","电脑死机",""],
                        ["high winds","疾风",""],
                        ["local heroes","当地的英雄",""],
                        ["learning zone","学习区",""],
                        ["cinema zone","电影区",""],
                        ["garden tools","园艺工具",""],
                        ["tap water","自来水",""],
                        ["special buses","特殊巴士",""],
                        ["order form","预订表格",""],
                        ["signed delivery note","签署过的交货通知",""],
                        ["black swans","黑天鹅",""],
                        ["historical exhibition","历史展览",""],
                        ["head office","总部",""],
                        ["classroom tour","参观教室",""],
                        ["chess club","象棋俱乐部",""],
                        ["animal life","动物生活",""],
                        ["annual report","年度报告",""],
                        ["total block","防晒霜",""],
                        ["secondary project","次要项目",""],
                        ["back entrance","后门",""],
                        ["emergency button","紧急按钮",""],
                        ["disabled people","残疾人",""],
                        ["minimum period","最小周期",""],
                        ["sports equipment","体育装备",""],
                        ["baby kangaroo","小袋鼠",""],
                        ["business courses","商科课程",""],
                        ["English channel","英吉利海峡",""],
                        ["tower view","高塔视野",""],
                        ["travel centre","旅游信息中心",""],
                        ["budget trip","预订旅行",""],
                        ["supportive atmosphere","声援气氛",""],
                        ["coffee machine","咖啡机",""],
                        ["seating area","休息区",""],
                        ["board games","桌游",""],
                        ["equal length","同样长度",""],
                        ["tutorial fee","辅导费用",""],
                        ["security officer","安保人员",""],
                        ["hot meal","热食",""],
                        ["music room","音乐室",""],
                        ["tea and coffee","茶和咖啡",""],
                        ["monthly magazines","月刊",""],
                        ["social event","社交活动",""],
                        ["spare socks","备用袜子",""],
                        ["local museum","当地博物馆",""],
                        ["late afternoon","傍晩",""],
                        ["storage space","储物空间",""],
                        ["hot spring","温泉",""],
                        ["specific period","特定时期",""],
                        ["health check","健康检查",""],
                        ["town hall","市政大厅",""],
                        ["part-time job","业余工作",""],
                        ["senior staff","高级员工",""],
                        ["tropical zone","热带地区",""],
                        ["elephant zone","大象区域",""],
                        ["travel package","旅行行李",""],
                        ["long vacation","长假期",""],
                        ["store room","储藏室",""],
                        ["front desk","前台",""],
                        ["local residents","当地居民",""],
                        ["massage room","按摩室",""],
                        ["training course","训练课程",""],
                        ["administration officer","管理员",""],
                        ["fire drill","火灾演练",""],
                        ["card making","卡片制作",""],
                        ["water colour painting","水彩画",""],
                        ["minimum age","最小年龄",""],
                        ["special price","特殊价格",""],
                        ["government fund","政府资金",""],
                        ["control room","控制室",""],
                        ["cup cleaning","杯子清理",""],
                        ["reset button","重置按钮",""],
                        ["contact number","联系电话",""],
                        ["stunning view","优美风景",""],
                        ["horseback riding","骑马",""],
                        ["wild animals","野生动物",""],
                        ["fancy dress","炫酷的衣服",""],
                        ["concert room","小音乐厅",""],
                        ["free transportation","免费交通",""],
                        ["thick trousers","厚裤子",""],
                        ["virtual volunteer","网络志愿者",""],
                        ["cake factory","蛋糕厂",""],
                        ["lookout point","观景台",""],
                        ["member restaurant","会员餐厅",""],
                        ["food containers","食物容器",""],
                        ["formal clothes","正装",""],
                        ["delivery note","交付单",""],
                        ["coach trip","训练旅程",""],
                        ["attraction zone","景区",""],
                        ["good washing facilities","高效清洗设备",""],
                        ["interior design","内部设计",""],
                        ["venue change","地点转移",""],
                        ["regional competition","地区竞赛",""],
                        ["mixed age","混合年龄",""],
                        ["Local communitv","当地居民",""],
                        ["waiting room","等候室",""],
                        ["animal protection","动物保护",""],
                        ["experience skills","经验技能",""],
                        ["art museum","艺术博物馆",""],
                        ["street art","街头艺术",""],
                        ["tented accommodation","帐篷住宿",""],
                        ["stress levels","压力水平",""],
                        ["family ticket","家庭套票",""],
                        ["weather observing","夭气观察",""],
                        ["fitness centre","健身中心",""],
                        ["shuttle buses","班车",""],
                        ["feed animals","喂动物",""],
                        ["smoke alarm","烟雾警报",""],
                        ["face painting","脸谱",""],
                        ["gallery shop","画廊",""],
                        ["good shoes","好鞋",""],
                        ["dance show","舞蹈表演",""],
                        ["mountain climbing","爬山",""],
                        ["bush fire","丛林火灾",""],
                        ["handle animals","驯养动物",""],
                        ["trial test","模拟测试",""],
                        ["provisional licence","临时证件",""],
                        ["pretzel factory","饼干厂",""],
                        ["prepare refreshments","准备点心",""],
                        ["hot balloon","热气球",""],
                        ["fast line ticket","快速通道票",""],
                        ["herbal treatment","草药治疗",""],
                        ["one-to-one coach","一对一教练",""],
                        ["gym room","健身房",""],
                        ["free massage","免费按摩",""],
                        ["beach front view","沙滩前景",""],
                        ["well-known singer","知名歌手",""],
                        ["ink cartridge","打印机墨盒",""],
                        ["meal ticket","餐券",""],
                        ["oil filter","油滤器",""],
                        ["loss of instruments","仪器损失",""],
                        ["marine animals","海洋动物",""],
                        ["meadow campsite","牧场野营地",""],
                        ["green lounge","绿色躺椅",""],
                        ["unregistered taxi","黑车",""],
                        ["compulsory modules","必修模块",""],
                        ["final score","最后分数",""],
                        ["wooden peg","木头桩",""],
                        ["roof scaffold","房顶脚手架",""],
                        ["hospital comedy","医院喜剧",""],
                        ["science fiction","科幻片",""],
                        ["practical theorv","实际理论",""],
                        ["train ride","火车之旅",""],
                        ["weather forecast","天气预报",""],
                        ["family-fast-line track","家庭快线票",""],
                        ["ticket","入场券",""],
                        ["cowboy show ride","牛仔表演之旅",""],
                        ["skating rink","溜冰场",""],
                        ["introductory price","人门价格",""],
                        ["heart monitor","心脏监视器",""],
                        ["water bottle","水瓶",""],
                        ["bright fabric","明亮织物",""],
                        ["bottle collection","瓶子收集",""],
                        ["picnic area","野餐区",""],
                        ["fuel consumption","燃料消耗",""],
                        ["global travel","全球旅行",""],
                        ["steer the boat","掌船舵",""],
                        ["marine history","海洋史",""],
                        ["caravan park","房车停车场",""],
                        ["cash point","ATM 取款机；现金处",""],
                        ["plastic bag","塑料袋",""],
                        ["objective matters","客观物质",""],
                        ["ancient history","远古历史",""],
                        ["animal bones","动物骨头",""],
                        ["changing room","更衣室",""],
                        ["family life","家庭生活",""],
                        ["heavy stuff","重物",""],
                        ["business district","商业区",""],
                        ["exotic plants","外国植物",""],
                        ["single session","单独课程",""],
                        ["police offence","袭警",""],
                        ["practical elements","实用元素",""],
                        ["compulsory course","必修课",""],
                        ["annual report","年报",""],
                        ["solar panels","太阳能板",""],
                        ["gas cooker","煤气灶",""],
                        ["campus clinic","校医院",""],
                        ["clothes manufacturing","服装制作",""],
                        ["fashion exhibition","时尚展览",""],
                        ["toy train","玩具火车",""],
                        ["free locker","免费储物柜",""],
                        ["curriculum vitae","简历",""],
                        ["luggage lockers","行李柜",""],
                        ["waiting room","等候室",""],
                        ["meadow campsite","草地露营地",""],
                        ["dinosaur bones","恐龙骨骼化 石",""],
                        ["artificial light","人造光",""],
                        ["racing car","赛车",""],
                        ["wood of hazel","榛树的木头",""],
                        ["heavy stuff","重的东西",""],
                        ["trade journals","贸易期刊",""],
                        ["residential area","居住区",""],
                        ["garden tools","园艺工貝",""],
                        ["building materials","建筑材料",""],
                        ["English proficiency","英语熟练度",""],
                        ["traffic violation","违反交规",""],
                        ["tuition fees","学费",""],
                        ["agriculture fair","农业集市",""],
                        ["electric card","电子卡",""],
                        ["electric cooker","电子炊具",""],
                        ["enquiry desk","问询台",""],
                        ["local owners","当地所有者",""],
                        ["professional model","专业模特",""],
                        ["limited time","有限的时间",""],
                        ["gift shop","礼品店",""],
                        ["personal belongings","个人物品",""],
                        ["volunteer list","志愿者名单",""],
                        ["bike racks","自行车架",""],
                        ["test room","考场",""],
                        ["green lounge","绿色的休息室",""],
                        ["night tour trip","夜游旅行",""],
                        ["mineral resources","矿产资源",""],
                        ["face painting","面部彩绘",""],
                        ["building wood","建筑木材",""],
                        ["annual report","年度报告",""],
                        ["guest speaker","特邀发言人",""],
                        ["troop exercises","军事演习",""],
                        ["wooden sculptures","木雕",""],
                        ["related project","相关项目",""],
                        ["heritage sites","遗迹",""],
                        ["formal gardens","正式花园",""],
                        ["palm trees","棕榈树",""],
                        ["extended family","大家庭",""],
                        ["tour manager","旅游经理",""],
                        ["adventure playground","冒险乐园",""],
                        ["wild flowers","野花",""],
                        ["group discussion marks","分数",""],
                        ["data analvsis","数据分析",""],
                        ["extra time","额外时间",""],
                        ["personal interest","个人兴趣",""],
                        ["middle term test","期中考试",""],
                        ["photo statistics","照片统计",""],
                        ["communication system","通信系统",""],
                        ["secretary of department","部门秘书",""],
                        ["computer office","电脑办公室",""],
                        ["international reputation","国际声誉",""],
                        ["conference report","会议报告",""],
                        ["chat rooms","聊天室",""],
                        ["teaching staff","教职人员",""],
                        ["eye contacts","眼神交流",""],
                        ["lack of soil","缺土",""],
                        ["environmental damage","（破坏）",""],
                        ["fill in worksheet","填工作单",""],
                        ["video camera","摄像机",""],
                        ["natural ability","自然能力",""],
                        ["leadership skill","领导力",""],
                        ["braking system","剎车系统",""],
                        ["management of change","改变管理",""],
                        ["working style","工作类型",""],
                        ["lack of research","缺乏调查",""],
                        ["knowledge sharing","知识共享",""],
                        ["seating capacity","载客数",""],
                        ["packing materials","包装材料",""],
                        ["stage production","舞台布置",""],
                        ["videotape editor","视频编辑",""],
                        ["interview method","面试方法",""],
                        ["weaker students","差生",""],
                        ["word limit","宇数限制",""],
                        ["past course materials","之前课程材料",""],
                        ["history research","历史调查",""],
                        ["ground plan","平面图",""],
                        ["computer skills","电脑技能",""],
                        ["global listening","宏观听力",""],
                        ["card catalogue","卡片目录",""],
                        ["food pest","食物害虫",""],
                        ["food chain","食物链",""],
                        ["model guide","模范导游",""],
                        ["measuring equipment","测量设备",""],
                        ["good effort","努力",""],
                        ["accessible discussion","可参加的讨论",""],
                        ["environmental issues","环境问题",""],
                        ["financial aids","经济援助",""],
                        ["late submission","延迟提交",""],
                        ["farming method","耕种方式",""],
                        ["uniform level","同一水平",""],
                        ["picture framing","构图",""],
                        ["story conference","故事会议",""],
                        ["planning meeting","计划会议",""],
                        ["population movement","人口流动",""],
                        ["exam preparation","备考",""],
                        ["external organisation","外部组织",""],
                        ["internet connections","网络连接",""],
                        ["professional learning","专业学习",""],
                        ["video recording","视频录制",""],
                        ["residence hall","学生宿舍",""],
                        ["financial planning","金融计划",""],
                        ["customer relationship","顾客关系",""],
                        ["interview questions","面试问题",""],
                        ["dress code","着装要求",""],
                        ["show off status","炫耀地位",""],
                        ["personal identity","个人验证",""],
                        ["storage warehouse","仓库",""],
                        ["creative ideas","创造性想法",""],
                        ["survey methods","调查方式",""],
                        ["permanent records","永久记录",""],
                        ["drinking machines","饮料机",""],
                        ["laundry service","洗衣服务",""],
                        ["self-access lab","自主实验室",""],
                        ["text structure","文章结构",""],
                        ["media studies","媒体学习",""],
                        ["environmental projects","环境项目",""],
                        ["listening task","听力任务",""],
                        ["compulsory course","必修课",""],
                        ["flexible-time study","兼职学习",""],
                        ["extinct volcano","死火山",""],
                        ["placement test","分班测试",""],
                        ["leisure activities","休闲活动",""],
                        ["visual aids","视觉辅助工具",""],
                        ["in-class simulation","课内模拟",""],
                        ["plastic bottle","塑料瓶",""],
                        ["life science","生命科学",""],
                        ["medical skills","医术",""],
                        ["department head","部门主管",""],
                        ["identity card","识别卡",""],
                        ["preserve memories","保存记忆",""],
                        ["reflect tastes","体现品位",""],
                        ["local community","当地社区",""],
                        ["social information","社会信息",""],
                        ["living expenses","生活花费",""],
                        ["flour outlet","面粉出口",""],
                        ["optional course","选修课",""],
                        ["cash machine","验钞机",""],
                        ["photocopy office","影印室",""],
                        ["electronic directory","电子目录",""],
                        ["digital history","数码史",""],
                        ["natural resources","自然资源",""],
                        ["global access","全球通用",""],
                        ["book loan","借书",""],
                        ["full-time study","全职学习",""],
                        ["active volcano","活火山",""],
                        ["cleaning products","清理产品",""],
                        ["company premises","公司地址",""],
                        ["senior adviser","高级顾问",""],
                        ["fossil remains","残存化石",""],
                        ["human interterence","人为干扰",""],
                        ["coffee bar","咖啡吧",""],
                        ["personal service","个人服务",""],
                        ["video approach","录像硏究 方法",""],
                        ["higher fees","更高价格",""],
                        ["confidence building","建立自信",""],
                        ["networking opportunities","网络机遇",""],
                        ["audio recording","音频录制",""],
                        ["community reference","社区推荐信",""],
                        ["renewable energy","再生资源",""],
                        ["traditional resource","传统资源",""],
                        ["solar panel","太阳能电池板",""],
                        ["poor paying","报酬低的",""],
                        ["no chemical reaction","无化学反应",""],
                        ["brief notes","简要记录",""],
                        ["essential training","基本训练",""],
                        ["background reading","背景阅读",""],
                        ["soil sample","土壤样本",""],
                        ["stress level","压力级别",""],
                        ["school gym","校健身房",""],
                        ["accurate date","确切日期",""],
                        ["sports activities","体育活动",""],
                        ["abstract design","抽象设计",""],
                        ["observation checklist","观察清单",""],
                        ["natural routine work","日常工作",""],
                        ["shop display","商品展示",""],
                        ["current study","当前研究",""],
                        ["job opportunities","工作机会",""],
                        ["borrowed language","外来语",""],
                        ["numeracy skill","计算箅能力",""],
                        ["research method","调查方式",""],
                        ["lack of participation","缺乏参与",""],
                        ["council meeting","议会会议",""],
                        ["nuclear plants","核电站",""],
                        ["small electric equipment","小电子设备",""],
                        ["sports shoes","运动鞋",""],
                        ["overseas training","海外训练",""],
                        ["current material","现有材料",""],
                        ["supportive atmosphere","互助气氛",""],
                        ["university support staff","大学服务人员",""],
                        ["online forum","在线论坛",""],
                        ["blood pressure","血压",""],
                        ["school stadiums","校体育馆",""],
                        ["less oxygen","缺氧",""],
                        ["similar age","相似年龄",""],
                        ["art institution","艺术机构",""],
                        ["largest proportion","最大比例",""],
                        ["non-observation method","非观察手段",""],
                        ["test results","测试结果",""],
                        ["wood curve","木材弯曲",""],
                        ["monitoring progress","监管进程",""],
                        ["team building","团队建设",""],
                        ["finding investment","寻找投资",""],
                        ["food shortage","食物缺乏",""],
                        ["visual guidance","视觉引导",""],
                        ["reference letter","推荐信",""],
                        ["lab facilities","实验室设备",""],
                        ["engine capacity","发动机容量",""],
                        ["safe car","安全车辆",""],
                        ["field of vision","视野",""],
                        ["economic purpose","经济目的",""],
                        ["cost of insurance","保险费用",""],
                        ["marine desert","海洋沙漠(沙漠名称）",""],
                        ["unexpected noise","未预料的噪声",""],
                        ["gradual way","渐进的方式",""],
                        ["local faculty","当地部门",""],
                        ["unanswered questions","未回答的问题",""],
                        ["practical knowledge","实用知识",""],
                        ["scientific term","科学术语",""],
                        ["seed germination","种子发芽",""],
                        ["housing project","住宅项目",""],
                        ["book allowance","图书津贴",""],
                        ["unexpected noise","意想不到的噪声",""],
                        ["social reforms","社会改革",""],
                        ["household appliances","家用设备",""],
                        ["colours and fonts","颜色和字体",""],
                        ["greater utility","更大的效用",""],
                        ["open day","开放日",""],
                        ["academic performance","学学业成绩",""],
                        ["conflicting opinions","意见冲突",""],
                        ["low impact","小冲击",""],
                        ["roads and bridges","路和桥",""],
                        ["persuasive writing","说服性文章",""],
                        ["ocean conditions","海洋条件",""],
                        ["simple memories","简单回忆",""],
                        ["digital store","数码商店",""],
                        ["bar code","条形码",""],
                        ["learning difficulty","学习障碍",""],
                        ["low nutrition","缺乏营养",""],
                        ["no change","无变化",""],
                        ["private property","私人财产",""],
                        ["specialised software","专业软件",""],
                        ["water pipes","水管",""],
                        ["action plan","行动计划",""],
                        ["road building","道路建设",""],
                        ["olive oil","橄榄油",""],
                        ["high temperatures","高温度",""],
                        ["fresh meat","鲜肉",""],
                        ["eating pattern","吃饭习惯",""],
                        ["water tanks","水箱",""],
                        ["car tax","购车稅",""],
                        ["textile factory","纺织厂",""],
                        ["video cameras","摄像机",""],
                        ["global warming","全球变暖",""],
                        ["social activities","社会活动",""],
                        ["internal flight","国内航线",""],
                        ["alternative energy","新能源",""],
                        ["high absence rate","高缺席率",""],
                        ["academic essays","学术论文",""],
                        ["study ability","学习能力",""],
                        ["information sector","信息部门",""],
                        ["volcanic dust","火山灰",""],
                        ["climate change","气候变化",""],
                        ["reading difficulty","阅读障碍",""],
                        ["desert habitat","沙漠栖息地",""],
                        ["extra resources","额外资源",""],
                        ["fruit growing","果树栽培",""],
                        ["chewing gum","口香糖",""],
                        ["big company","大公司",""],
                        ["window glass","窗玻璃",""],
                        ["knife handle","刀柄",""],
                        ["goat skin","山羊皮",""],
                        ["land bridge","陆桥",""],
                        ["food intake","食物摄入",""],
                        ["transport museum","交通博物馆",""],
                        ["government election","政府选举",""],
                        ["food chain","食物链",""],
                        ["tea tree oil","茶树油",""],
                        ["carbon dioxide","二氧化碳",""],
                        ["online service","在线服务",""],
                        ["further training","迸阶训练",""],
                        ["traffic flow","车流量",""],
                        ["short stroke","短笔画（写宇）",""],
                        ["group meeting","团队会议",""],
                        ["mission statement","任务清单",""],
                        ["soil damage","土壤损害",""],
                        ["fish bones","鱼骨",""],
                        ["absence rate","缺席率",""],
                        ["transport service","运输服务",""],
                        ["public square","广场",""],
                        ["vertical cabin","垂直座舱",""],
                        ["voices and faces","声音和脸",""],
                        ["red blood cell","红细胞",""],
                        ["grain pattern","谷物图案",""],
                        ["streets and roads","街道和公路",""],
                        ["extra resources","额外资源",""],
                        ["natural fibre","夭然纤维",""],
                        ["carbon mining","碳矿",""],
                        ["known world","熟悉的世界",""],
                        ["Roman emperor","罗马皇帝",""],
                        ["law firm","律师事务所",""],
                        ["market share","市场占有率",""],
                        ["habitat loss","栖息地丧失",""],
                        ["zero noisy","无噪声的",""],
                        ["land resources","陆地资源",""],
                        ["hospitality industry","酒店业",""],
                        ["language barrier","语言障碍",""],
                        ["food prices","食物价格",""],
                        ["large-scale housing","大面积住房区域",""],
                        ["standard feedback","标准反馈",""],
                        ["training session","训练阶段",""],
                        ["broken axe","损坏的斧子",""],
                        ["triangle-shaped","三角形的",""],
                        ["green tax","环保稅",""],
                        ["sleeping disturbance","睡眠障碍",""],
                        ["feeding time","喂食时间",""],
                        ["ask for apology","寻求道歉",""],
                        ["heart rate","心率",""],
                        ["Indian tribes","印第安部落",""],
                        ["prime motivation","主要动机",""],
                        ["forest planet","森林星球",""],
                        ["ship building","造船",""],
                        ["melting pot","熔炉",""],
                        ["fishing lesson","钓鱼课程",""],
                        ["silver coins","银币",""],
                        ["social conformity","社会从众性",""],
                        ["protective clothing","防护衣物",""],
                        ["reflective practice","应激训练",""],
                        ["rich experiences","丰富经历",""],
                        ["durable contracture","持久性痉孪",""],
                        ["fish farming","鱼类养殖",""],
                        ["time and sequence","时间和顺序",""],
                        ["wealthy people","富有的人",""],
                        ["presence rate","出勤率",""],
                        ["direct route","直达路线",""],
                        ["operation manager","执行经理",""],
                        ["rare glass","稀有玻璃",""],
                        ["social glue","社会黏性",""],
                        ["transport system","交通系统",""],
                        ["boring content","乏味的内容",""],
                        ["regular basis","常规基础",""],
                        ["lifestyle sports","生活方式运动（运动名称）",""],
                        ["traditional sports","传统运动",""],
                        ["regular training","常规训练",""],
                        ["sense of community","社区意识",""],
                        ["rice cultivation","稻株栽培",""],
                        ["glass bottle","玻璃瓶",""],
                        ["sand base","沙基",""],
                        ["fibre diet","纤维食物",""],
                        ["average size","平均尺寸",""],
                        ["major illness","主要的疾病",""],
                        ["physical changes","物理变化",""],
                        ["dark blue veil","深蓝色面纱",""],
                        ["migration patterns","𨑳徙类型",""],
                        ["mineral soil","矿物质土壤",""],
                        ["soft sediment","松软沉积物",""],
                        ["estate agent","房产经纪人",""],
                        ["emergency locator beacon","应急定位器信标",""],
                        ["tracking devices","跟踪设备",""],
                        ["fish hooks","鱼钩",""],
                        ["cooperation process","合作过程",""],
                        ["carpet case","地毯箱",""],
                        ["hand torch","手电简",""],
                        ["traditional lecture","传统课程",""],
                        ["extreme sports","极限运动",""],
                        ["better equipment","更好的设备",""],
                        ["restricted regulations","限制规定",""],
                        ["individual competition","个人竞争",""],
                        ["salt content","盐分含量",""],
                        ["skin of frog","青蛙的皮肤",""],
                        ["open roof","开放式房顶",""],
                        ["high protein","高蛋白",""],
                        ["constant temperature","恒温",""],
                        ["good eyesight","好视力",""],
                        ["quality of life","生活质量",""],
                        ["particular disease","特殊疾病",""],
                        ["scientific backup","科学支持",""],
                        ["preserved remains","保留的遗迹",""],
                        ["tape measure","卷尺",""],
                        ["plant pot","植物盆栽",""],
                        ["botanic garden","植物园",""],
                        ["digestive problem","消化问题",""],
                        ["red blood cells","红细胞",""],
                        ["fishing net","渔网",""],
                        ["mineral soil","矿物土壤",""],
                        ["stored temperature","储存温度",""],
                        ["migration patterns","迁移模式",""],
                        ["goat skin","山羊皮",""],
                        ["mission statement","使命宣言",""],
                        ["machines or robots","机器或机器人",""],
                        ["rubber tyre","橡胶轮胎",""],
                        ["southern Scotland","苏格兰南部",""],
                        ["global market","全球市场",""],
                        ["feeding time","喂食的时候",""],
                        ["silver coins","银币",""],
                        ["hinder domestic smells","阻碍内部的气味",""],
                        ["ship building","造船业",""],
                        ["gum tree","胶树",""],
                        ["multiple tasks","多种工作",""],
                        ["weight loss","减肥",""],
                        ["pigeons and rats","鸽子和老鼠",""],
                        ["still water","静止的水",""],
                        ["frozen food","冷冻食品",""],
                        ["olive oil","橄榄油",""],
                        ["particular disease","特定疾病",""],
                        ["administration officer","行政官员",""],
                        ["smooth ride","平稳行驶",""],
                        ["desert locations","沙漠地区",""],
                        ["head offices","总部",""],
                        ["safe environment","安全的环境",""],
                        ["hearing loss","听力损失",""],
                        ["maintain the gene diversity","保持基因多样性",""],
                        ["transport costs","运输成本",""],
                        ["cleansing properties","清洁特性",""],
                        ["gene diversity","基因多样化",""]
                )
                return words

        def bookWordsThird(self):
                words = (
                        
                     )
                return words
